-- Expand BusinessType enum with new values for multi-vertical support
-- Adding values for: FOOD_SERVICE, RETAIL, SERVICES, HOSPITALITY, ENTERTAINMENT categories

-- FOOD_SERVICE additions (RESTAURANT already exists)
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'BAR';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'CAFE';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'BAKERY';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'FOOD_TRUCK';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'FAST_FOOD';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'CATERING';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'CLOUD_KITCHEN';

-- RETAIL additions (RETAIL already exists, renaming concept to RETAIL_STORE)
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'RETAIL_STORE';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'JEWELRY';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'CLOTHING';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'ELECTRONICS';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'PHARMACY';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'CONVENIENCE_STORE';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'SUPERMARKET';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'LIQUOR_STORE';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'FURNITURE';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'HARDWARE';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'BOOKSTORE';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'PET_STORE';

-- SERVICES additions (SPA, FITNESS already exist)
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'SALON';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'CLINIC';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'VETERINARY';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'AUTO_SERVICE';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'LAUNDRY';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'REPAIR_SHOP';

-- HOSPITALITY additions (HOTEL already exists)
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'HOSTEL';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'RESORT';

-- ENTERTAINMENT additions
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'CINEMA';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'ARCADE';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'EVENT_VENUE';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'NIGHTCLUB';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'BOWLING';
