/**
 * Procurement read tools (coverage-gap sweep, 2026-06-29): suppliers + purchase orders
 * shipped on the dashboard (inventory.routes) but had no MCP coverage.
 *
 *   - list_suppliers        — proveedores (contact, rating, lead time, min order)
 *   - list_purchase_orders  — órdenes de compra (status, supplier, total, item count)
 *   - purchase_order_detail — line items of one order (qty ordered vs received, prices)
 *
 * All reads, venue-scoped, PREMIUM-gated (INVENTORY_TRACKING) — same gate as every other
 * inventory read tool (low_stock / stock_value / kardex). Money in PESOS, 1:1.
 */
import { registerProcurementTools } from '../../../src/mcp/tools/procurement'
import type { McpScope } from '../../../src/mcp/scope'

const mockGetSuppliers = jest.fn()
const mockGetPurchaseOrders = jest.fn()
const mockGetPurchaseOrder = jest.fn()
const mockPlanGate = jest.fn()

jest.mock('@/services/dashboard/supplier.service', () => ({ getSuppliers: (...a: unknown[]) => mockGetSuppliers(...(a as [])) }))
jest.mock('@/services/dashboard/purchaseOrder.service', () => ({
  getPurchaseOrders: (...a: unknown[]) => mockGetPurchaseOrders(...(a as [])),
  getPurchaseOrder: (...a: unknown[]) => mockGetPurchaseOrder(...(a as [])),
}))
jest.mock('@/mcp/planGate', () => ({ planGateMessage: (...a: unknown[]) => mockPlanGate(...(a as [])) }))
jest.mock('@/mcp/guard', () => ({
  createGuard: () => ({
    venueFilter: (v?: string) => {
      if (v && v !== 'v1') throw new Error('ScopeError: venue out of scope')
      return { venueId: { in: ['v1'] } }
    },
    requirePermission: jest.fn(),
  }),
}))

const handlers = new Map<string, (a: Record<string, unknown>, e: unknown) => Promise<{ content: Array<{ text: string }> }>>()
const scope = { staffId: 's1', activeOrg: 'o1', allowedVenueIds: ['v1'], perVenueAccess: new Map() } as McpScope
const call = (n: string, args: Record<string, unknown>) => handlers.get(n)!(args, {})
const parse = (r: { content: Array<{ text: string }> }) => JSON.parse(r.content[0].text)

beforeAll(() => {
  registerProcurementTools({ tool: (...a: unknown[]) => handlers.set(a[0] as string, a[a.length - 1] as never) } as never, scope)
})
beforeEach(() => {
  jest.clearAllMocks()
  mockPlanGate.mockResolvedValue(null) // entitled (PREMIUM) by default
})

describe('list_suppliers (read, PREMIUM-gated)', () => {
  it('rejects an out-of-scope venue', async () => {
    await expect(call('list_suppliers', { venueId: 'foreign' })).rejects.toThrow('out of scope')
  })

  it('fires the PREMIUM gate when the venue lacks INVENTORY_TRACKING', async () => {
    mockPlanGate.mockResolvedValueOnce('El control de inventario requiere PREMIUM')
    const out = parse(await call('list_suppliers', { venueId: 'v1' }))
    expect(out.planRequired).toBe(true)
    expect(mockGetSuppliers).not.toHaveBeenCalled()
  })

  it('defaults to active suppliers and maps Decimal fields to numbers', async () => {
    mockGetSuppliers.mockResolvedValueOnce([
      {
        id: 'sup1',
        name: 'Bimbo',
        contactName: 'Juan',
        email: 'j@b.com',
        phone: '55',
        rating: 4.5,
        leadTimeDays: 2,
        minimumOrder: 500,
        active: true,
      },
    ])
    const out = parse(await call('list_suppliers', { venueId: 'v1' }))
    expect(mockGetSuppliers).toHaveBeenCalledWith('v1', { active: true })
    expect(out.suppliers[0]).toMatchObject({ id: 'sup1', name: 'Bimbo', rating: 4.5, leadTimeDays: 2, minimumOrder: 500, active: true })
  })

  it('includeInactive drops the active filter; search is forwarded', async () => {
    mockGetSuppliers.mockResolvedValueOnce([])
    await call('list_suppliers', { venueId: 'v1', includeInactive: true, search: 'bim' })
    expect(mockGetSuppliers).toHaveBeenCalledWith('v1', { search: 'bim' })
  })
})

describe('list_purchase_orders (read, PREMIUM-gated)', () => {
  it('maps orders (total as number, item count, autoGenerated) and forwards status', async () => {
    mockGetPurchaseOrders.mockResolvedValueOnce([
      {
        id: 'po1',
        orderNumber: 'OC-001',
        supplier: { name: 'Bimbo' },
        status: 'PENDING_APPROVAL',
        orderDate: new Date('2026-06-20T10:00:00Z'),
        expectedDeliveryDate: new Date('2026-06-25T10:00:00Z'),
        receivedDate: null,
        total: 1160,
        items: [{}, {}],
        autoGenerated: true,
      },
    ])
    const out = parse(await call('list_purchase_orders', { venueId: 'v1', status: 'pending_approval' }))
    expect(mockGetPurchaseOrders).toHaveBeenCalledWith('v1', { status: ['PENDING_APPROVAL'] })
    expect(out.purchaseOrders[0]).toMatchObject({
      orderNumber: 'OC-001',
      supplier: 'Bimbo',
      status: 'PENDING_APPROVAL',
      total: 1160,
      itemCount: 2,
      autoGenerated: true,
    })
  })

  it('omits the status filter when not given', async () => {
    mockGetPurchaseOrders.mockResolvedValueOnce([])
    await call('list_purchase_orders', { venueId: 'v1' })
    expect(mockGetPurchaseOrders).toHaveBeenCalledWith('v1', {})
  })
})

describe('purchase_order_detail (read, PREMIUM-gated)', () => {
  it('returns the line items with qty ordered vs received and prices', async () => {
    mockGetPurchaseOrder.mockResolvedValueOnce({
      id: 'po1',
      orderNumber: 'OC-001',
      status: 'PARTIAL',
      supplier: { name: 'Bimbo', contactName: 'Juan', email: 'j@b.com', phone: '55' },
      orderDate: new Date('2026-06-20T10:00:00Z'),
      expectedDeliveryDate: null,
      receivedDate: null,
      subtotal: 1000,
      taxAmount: 160,
      total: 1160,
      autoGenerated: false,
      approvedAt: null,
      rejectionReason: null,
      notes: 'urgente',
      items: [
        {
          rawMaterial: { name: 'Harina', sku: 'HAR-1', unit: 'KG' },
          unit: 'KG',
          quantityOrdered: 50,
          quantityReceived: 20,
          receiveStatus: 'PARTIAL',
          unitPrice: 20,
          total: 1000,
        },
      ],
    })
    const out = parse(await call('purchase_order_detail', { venueId: 'v1', purchaseOrderId: 'po1' }))
    expect(out.found).toBe(true)
    expect(out.purchaseOrder).toMatchObject({ orderNumber: 'OC-001', subtotal: 1000, taxAmount: 160, total: 1160, notes: 'urgente' })
    expect(out.purchaseOrder.supplier).toMatchObject({ name: 'Bimbo', phone: '55' })
    expect(out.purchaseOrder.items[0]).toEqual({
      material: 'Harina',
      sku: 'HAR-1',
      unit: 'KG',
      quantityOrdered: 50,
      quantityReceived: 20,
      receiveStatus: 'PARTIAL',
      unitPrice: 20,
      total: 1000,
    })
  })

  it('returns found:false when the order is not in this venue', async () => {
    mockGetPurchaseOrder.mockResolvedValueOnce(null)
    const out = parse(await call('purchase_order_detail', { venueId: 'v1', purchaseOrderId: 'nope' }))
    expect(out.found).toBe(false)
    expect(mockGetPurchaseOrder).toHaveBeenCalledWith('v1', 'nope')
  })

  it('fires the PREMIUM gate before reading', async () => {
    mockPlanGate.mockResolvedValueOnce('El control de inventario requiere PREMIUM')
    const out = parse(await call('purchase_order_detail', { venueId: 'v1', purchaseOrderId: 'po1' }))
    expect(out.planRequired).toBe(true)
    expect(mockGetPurchaseOrder).not.toHaveBeenCalled()
  })
})
