import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { z } from 'zod'
import type { McpScope } from '../scope'
import { createGuard } from '../guard'
import { text } from '../respond'
import { planGateMessage } from '../planGate'
import { getSuppliers } from '@/services/dashboard/supplier.service'
import { getPurchaseOrders, getPurchaseOrder } from '@/services/dashboard/purchaseOrder.service'
import { PurchaseOrderStatus } from '@prisma/client'

// Procurement (suppliers + purchase orders) is part of inventory — gate it exactly like the
// other inventory READ tools: the PREMIUM INVENTORY_TRACKING feature. Reads, so venue-scoped
// (own venues only) but no per-action permission, matching low_stock / stock_value / kardex.
const INVENTORY_GATE = ['INVENTORY_TRACKING', 'El control de inventario'] as const

const PO_STATUS_MAP: Record<string, PurchaseOrderStatus> = {
  draft: PurchaseOrderStatus.DRAFT,
  pending_approval: PurchaseOrderStatus.PENDING_APPROVAL,
  rejected: PurchaseOrderStatus.REJECTED,
  approved: PurchaseOrderStatus.APPROVED,
  sent: PurchaseOrderStatus.SENT,
  confirmed: PurchaseOrderStatus.CONFIRMED,
  shipped: PurchaseOrderStatus.SHIPPED,
  partial: PurchaseOrderStatus.PARTIAL,
  received: PurchaseOrderStatus.RECEIVED,
  cancelled: PurchaseOrderStatus.CANCELLED,
}

// Decimal | number | null → number | null (pesos, 1:1 — never cents).
const num = (v: unknown): number | null => (v == null ? null : Number(v))

export function registerProcurementTools(server: McpServer, scope: McpScope) {
  const guard = createGuard(scope)

  server.tool(
    'list_suppliers',
    'Suppliers / vendors (proveedores) of a venue you can access: name, contact (person, email, phone), rating, average lead time (days to deliver), minimum order value, and whether active. Defaults to active suppliers. Optionally filter by a name/contact/email search. Answers "¿qué proveedores tengo? ¿a quién le compro X? ¿cuál es el más confiable?". Pass venueId. PREMIUM (INVENTORY_TRACKING). For their orders use list_purchase_orders.',
    {
      venueId: z.string().describe('Venue whose suppliers to list (must be in your scope)'),
      search: z.string().optional().describe('Filter by name / contact / email (partial, case-insensitive)'),
      includeInactive: z.boolean().optional().describe('Also include inactive suppliers (default: only active)'),
      limit: z.number().int().positive().max(100).optional().describe('Max suppliers to return (default 50)'),
    },
    async ({ venueId, search, includeInactive, limit }) => {
      guard.venueFilter(venueId) // throws ScopeError if the venue is out of scope
      const gate = await planGateMessage(venueId, ...INVENTORY_GATE) // PREMIUM tier — mirrors inventory reads
      if (gate) return text({ ok: false, planRequired: true, error: gate })

      const suppliers = await getSuppliers(venueId, {
        ...(includeInactive ? {} : { active: true }),
        ...(search ? { search } : {}),
      })
      const rows = suppliers.slice(0, limit ?? 50)
      return text({
        venueId,
        count: rows.length,
        suppliers: rows.map(s => ({
          id: s.id,
          name: s.name,
          contactName: s.contactName,
          email: s.email,
          phone: s.phone,
          rating: num(s.rating), // 1.0–5.0
          leadTimeDays: s.leadTimeDays,
          minimumOrder: num(s.minimumOrder), // pesos
          active: s.active,
        })),
      })
    },
  )

  server.tool(
    'list_purchase_orders',
    'Purchase orders (órdenes de compra) of a venue you can access: order number, supplier, status (draft/pending_approval/approved/sent/received/cancelled…), order date, expected delivery, total amount (pesos), how many line items, and whether it was auto-generated by the reorder job. Newest first. Filter by status. Answers "¿qué órdenes de compra tengo pendientes? ¿qué le pedí a tal proveedor? ¿cuáles ya llegaron?". Pass venueId. PREMIUM (INVENTORY_TRACKING). For the line items of one order use purchase_order_detail.',
    {
      venueId: z.string().describe('Venue whose purchase orders to list (must be in your scope)'),
      status: z
        .enum(['draft', 'pending_approval', 'rejected', 'approved', 'sent', 'confirmed', 'shipped', 'partial', 'received', 'cancelled'])
        .optional()
        .describe('Filter by status (omit for all)'),
      limit: z.number().int().positive().max(100).optional().describe('Max orders to return (default 25, newest first)'),
    },
    async ({ venueId, status, limit }) => {
      guard.venueFilter(venueId) // throws ScopeError if the venue is out of scope
      const gate = await planGateMessage(venueId, ...INVENTORY_GATE) // PREMIUM tier
      if (gate) return text({ ok: false, planRequired: true, error: gate })

      const orders = await getPurchaseOrders(venueId, {
        ...(status ? { status: [PO_STATUS_MAP[status]] } : {}),
      })
      const rows = orders.slice(0, limit ?? 25)
      return text({
        venueId,
        count: rows.length,
        purchaseOrders: rows.map(po => ({
          id: po.id,
          orderNumber: po.orderNumber,
          supplier: (po as { supplier?: { name?: string } }).supplier?.name ?? null,
          status: po.status,
          orderDate: po.orderDate.toISOString(),
          expectedDeliveryDate: po.expectedDeliveryDate?.toISOString() ?? null,
          receivedDate: po.receivedDate?.toISOString() ?? null,
          total: num(po.total), // pesos
          itemCount: (po as { items?: unknown[] }).items?.length ?? 0,
          autoGenerated: po.autoGenerated, // true = created by the auto-reorder job
        })),
      })
    },
  )

  server.tool(
    'purchase_order_detail',
    'Full detail of ONE purchase order in a venue you can access, by its id (from list_purchase_orders): supplier + contact, status, order/expected/received dates, amounts (subtotal, tax, total — pesos), whether auto-generated, approval/rejection info, notes, and every LINE ITEM (raw material, unit, quantity ordered vs received, receive status, unit price, line total). Answers "¿qué traía la orden OC-123? ¿cuánto recibí de cada cosa?". Pass venueId + purchaseOrderId.',
    {
      venueId: z.string().describe('Venue that owns the order (must be in your scope)'),
      purchaseOrderId: z.string().min(1).describe('Purchase order id (from list_purchase_orders)'),
    },
    async ({ venueId, purchaseOrderId }) => {
      guard.venueFilter(venueId) // throws ScopeError if the venue is out of scope
      const gate = await planGateMessage(venueId, ...INVENTORY_GATE) // PREMIUM tier
      if (gate) return text({ ok: false, planRequired: true, error: gate })

      const po = await getPurchaseOrder(venueId, purchaseOrderId)
      if (!po) return text({ found: false, error: `No encontré la orden de compra "${purchaseOrderId}" en este local.` })

      const supplier = (po as { supplier?: { name?: string; contactName?: string | null; email?: string | null; phone?: string | null } })
        .supplier
      const items = (
        po as {
          items?: Array<{
            rawMaterial?: { name?: string; sku?: string | null; unit?: string } | null
            unit: string
            quantityOrdered: unknown
            quantityReceived: unknown
            receiveStatus: string
            unitPrice: unknown
            total: unknown
          }>
        }
      ).items
      return text({
        found: true,
        purchaseOrder: {
          id: po.id,
          orderNumber: po.orderNumber,
          status: po.status,
          supplier: supplier
            ? {
                name: supplier.name ?? null,
                contactName: supplier.contactName ?? null,
                email: supplier.email ?? null,
                phone: supplier.phone ?? null,
              }
            : null,
          orderDate: po.orderDate.toISOString(),
          expectedDeliveryDate: po.expectedDeliveryDate?.toISOString() ?? null,
          receivedDate: po.receivedDate?.toISOString() ?? null,
          subtotal: num(po.subtotal),
          taxAmount: num(po.taxAmount),
          total: num(po.total),
          autoGenerated: po.autoGenerated,
          approvedAt: po.approvedAt?.toISOString() ?? null,
          rejectionReason: po.rejectionReason ?? null,
          notes: po.notes ?? null,
          items: (items ?? []).map(it => ({
            material: it.rawMaterial?.name ?? null,
            sku: it.rawMaterial?.sku ?? null,
            unit: it.unit,
            quantityOrdered: num(it.quantityOrdered),
            quantityReceived: num(it.quantityReceived),
            receiveStatus: it.receiveStatus, // PENDING | PARTIAL | RECEIVED …
            unitPrice: num(it.unitPrice), // pesos
            total: num(it.total), // pesos
          })),
        },
      })
    },
  )
}
