/** Directory catalog (`/mcp/directory`), published in tiers. A tool is excluded until its tier is reviewed and
 * MCP_DIRECTORY_TIER exposes it. The manual endpoint keeps its full catalog. This distribution boundary never
 * grants venue permissions or bypasses plan/activation gates.
 * Never listed here: moving money, government identifiers/CFDI/payroll, selling plans, internal administration.
 */
export const DIRECTORY_TIERS: ReadonlyArray<{ name: string; tools: readonly string[] }> = [
  {
    name: 'base',
    tools: [
      'list_my_organizations',
      'list_my_venues',
      'venue_profile',
      'daily_sales',
      'top_products',
      'category_mix',
      'sales_by_payment_method',
      'peak_hours',
      'channel_mix',
      'revenue_by_venue',
      'sales_comparison',
      'today_overview',
      'list_menu',
      'menu_categories',
      'menu_item_detail',
      'low_stock',
      'stock_value',
      'get_inventory_movements',
      'list_raw_materials',
      'list_product_recipes',
      'get_recipe',
      'list_suppliers',
      'create_category',
      'create_product',
      'set_menu_item_price',
      'set_menu_item_active',
      'create_raw_material',
      'update_raw_material',
      'adjust_raw_material_stock',
      'adjust_stock',
      'create_recipe',
      'enable_recipe_inventory',
      'create_supplier',
    ],
  },
  {
    // Consultas de la operación diaria: reservas, clientes, órdenes, caja, personal, compras, reseñas.
    name: 'lecturas',
    tools: [
      'accounting_income_statement',
      'accounting_banks_summary',
      'bank_reconciliation_summary',
      'area_ticket_status',
      'pending_area_ticket_deliveries',
      'area_ticket_reconciliation_queue',
      'pending_external_confirmations',
      'list_customer_campaigns',
      'birthday_automation_status',
      'list_commission_schemes',
      'list_commission_goals',
      'commission_payouts',
      'staff_commission',
      'list_credit_packs',
      'customer_credit_balance',
      'list_customer_groups',
      'customer_group_detail',
      'find_customer',
      'customer_history',
      'customers_awaiting_approval',
      'delivery_activation_requests',
      'delivery_channels',
      'delivery_courier',
      'delivery_line_actions',
      'list_discounts',
      'list_inter_venue_transfers',
      'inter_venue_transfer_detail',
      'reorder_suggestions',
      'stock_counts',
      'raw_material_presentations',
      'stock_batches',
      'inventory_postings',
      'list_waste_reports',
      'loyalty_status',
      'wallet_card_design',
      'stamp_card_status',
      'recent_orders',
      'find_order',
      'open_orders',
      'search_orders',
      'list_payment_effects',
      'list_payment_links',
      'list_payments',
      'list_refunds',
      'list_printers',
      'list_print_stations',
      'print_routing_preview',
      'list_kitchen_tickets',
      'list_purchase_orders',
      'purchase_order_detail',
      'product_sales',
      'list_promotions',
      'promotion_status',
      'promotion_sales',
      'referral_status',
      'reservations',
      'reservation_detail',
      'reservation_settings',
      'my_class_now',
      'staff_schedule',
      'service_staff',
      'list_class_sessions',
      'class_session_detail',
      'list_waitlist',
      'list_reviews',
      'staff_ranking',
      'tips_over_time',
      'staff_tips',
      'settlement_calendar',
      'settlement_week',
      'available_balance',
      'export_sales_summary',
      'service_charges',
      'list_shifts',
      'get_cash_drawer_status',
      'list_cash_drawer_sessions',
      'cash_closeout',
      'who_is_late_now',
      'work_shifts',
      'list_staff',
      'attendance_payroll_summary',
      'venue_attendance',
      'staff_detail',
      'tables_status',
      'list_areas',
      'list_tender_types',
      'tender_commissions',
      'audit_terminals',
      'list_devices',
      'terminal_checkout_screens',
      'terminal_payment_requests',
      'upsell_status',
    ],
  },
  {
    // Cambios internos de la operación: sin mensajes a terceros ni dinero de cuentas abiertas.
    name: 'escrituras',
    tools: [
      'set_customer_tags',
      'add_customer_note',
      'create_discount',
      'create_coupon',
      'create_promotion',
      'create_inter_venue_transfer',
      'approve_inter_venue_transfer',
      'reject_inter_venue_transfer',
      'cancel_inter_venue_transfer',
      'dispatch_inter_venue_transfer',
      'receive_inter_venue_transfer',
      'resolve_inter_venue_transfer_variance',
      'cancel_stock_count',
      'set_raw_material_presentations',
      'quarantine_batch',
      'log_waste',
      'configure_loyalty',
      'create_modifier_group',
      'undo_check_in',
      'set_staff_schedule',
      'set_service_staff',
      'set_table_status',
      'move_table_check',
      'assign_table_check',
      'split_table_check',
      'split_table_check_by_seat',
      'merge_table_check',
    ],
  },
]

/** MCP_DIRECTORY_TIER = índice de la última tanda expuesta. Ausente o inválido ⇒ sólo la base, nunca más. */
export function parseDirectoryTier(raw: string | undefined): number {
  if (raw === undefined || !/^\d+$/.test(raw.trim())) return 0
  return Math.min(Number(raw.trim()), DIRECTORY_TIERS.length - 1)
}

export function directoryToolsForTier(tier: number): Set<string> {
  return new Set(DIRECTORY_TIERS.slice(0, tier + 1).flatMap(t => t.tools))
}

export const CURRENT_DIRECTORY_TIER = parseDirectoryTier(process.env.MCP_DIRECTORY_TIER)
export const DIRECTORY_TOOLS = directoryToolsForTier(CURRENT_DIRECTORY_TIER)

export type McpProfile = 'manual' | 'directory'
