import { recordPaymentBodySchema } from '@/schemas/tpv.schema'

const cardPayment = {
  venueId: 'cmn3acoxt000mn227k1vdgj95',
  amount: 44000,
  tip: 0,
  status: 'COMPLETED',
  method: 'CREDIT_CARD',
  source: 'TPV',
  splitType: 'FULLPAYMENT',
  staffId: 'staff-1',
  paidProductsId: [],
  currency: 'MXN',
  merchantAccountId: 'cmn3a6xr8000kn227eg8zeh41',
  maskedPan: '477291******5280',
}

describe('recordPaymentBodySchema internationality evidence', () => {
  it('keeps old TPV payloads valid and defaults the legacy boolean', () => {
    const parsed = recordPaymentBodySchema.parse({ body: cardPayment })

    expect(parsed.body.isInternational).toBe(false)
    expect(parsed.body.issuerCountryCode).toBeUndefined()
    expect(parsed.body.issuerCountrySource).toBeUndefined()
  })

  it('accepts additive EMV evidence without changing the legacy boolean', () => {
    const parsed = recordPaymentBodySchema.parse({
      body: {
        ...cardPayment,
        isInternational: true,
        issuerCountryCode: '0840',
        issuerCountrySource: 'EMV_5F28',
      },
    })

    expect(parsed.body.isInternational).toBe(true)
    expect(parsed.body.issuerCountryCode).toBe('0840')
    expect(parsed.body.issuerCountrySource).toBe('EMV_5F28')
  })

  it('discards malformed shadow evidence instead of blocking the payment', () => {
    const parsed = recordPaymentBodySchema.parse({
      body: {
        ...cardPayment,
        issuerCountryCode: 'THIS-IS-NOT-A-COUNTRY-CODE',
        issuerCountrySource: 'SDK_GUESS',
      },
    })

    expect(parsed.body.issuerCountryCode).toBeUndefined()
    expect(parsed.body.issuerCountrySource).toBeUndefined()
  })
})

describe('recordPaymentBodySchema terminalPaymentRequestId length', () => {
  // Real incident (2026-08-07): payments whose terminalPaymentRequestId was 7
  // chars ("qa-qr-1") were rejected 400 → permanently stuck in the offline
  // queue with a banner the cashier can never clear. The field is a POS-echoed
  // correlation key: an unknown/short id is a harmless no-op on the server
  // (closeRowFromPaymentTx findUnique → miss → return), so length must NEVER
  // reject a money recording. Strict validation belongs at request creation,
  // not at recording time.
  it('accepts a short (7-char) terminalPaymentRequestId instead of stranding the payment', () => {
    const parsed = recordPaymentBodySchema.parse({
      body: { ...cardPayment, terminalPaymentRequestId: 'qa-qr-1' },
    })

    expect(parsed.body.terminalPaymentRequestId).toBe('qa-qr-1')
  })

  it('still rejects an empty terminalPaymentRequestId', () => {
    expect(() =>
      recordPaymentBodySchema.parse({
        body: { ...cardPayment, terminalPaymentRequestId: '' },
      }),
    ).toThrow()
  })

  it('still rejects a terminalPaymentRequestId over 64 chars', () => {
    expect(() =>
      recordPaymentBodySchema.parse({
        body: { ...cardPayment, terminalPaymentRequestId: 'x'.repeat(65) },
      }),
    ).toThrow()
  })

  // REGRESSION: idempotencyKey keeps min(8) ON PURPOSE. It is generated by OUR
  // TPV (always a UUID) and its length is load-bearing: it feeds the
  // (venueId, idempotencyKey) dedup that prevents double charges — short keys
  // raise collision risk between DIFFERENT payments. Do not relax it.
  it('still rejects a short idempotencyKey (dedup key stays strict)', () => {
    expect(() =>
      recordPaymentBodySchema.parse({
        body: { ...cardPayment, idempotencyKey: 'short' },
      }),
    ).toThrow()
  })
})
