import { recordPaymentBodySchema } from '@/schemas/tpv.schema'

const cardPayment = {
  venueId: 'cmn3acoxt000mn227k1vdgj95',
  amount: 44000,
  tip: 0,
  status: 'COMPLETED',
  method: 'CREDIT_CARD',
  source: 'TPV',
  splitType: 'FULLPAYMENT',
  staffId: 'staff-1',
  paidProductsId: [],
  currency: 'MXN',
  merchantAccountId: 'cmn3a6xr8000kn227eg8zeh41',
  maskedPan: '477291******5280',
}

describe('recordPaymentBodySchema internationality evidence', () => {
  it('keeps old TPV payloads valid and defaults the legacy boolean', () => {
    const parsed = recordPaymentBodySchema.parse({ body: cardPayment })

    expect(parsed.body.isInternational).toBe(false)
    expect(parsed.body.issuerCountryCode).toBeUndefined()
    expect(parsed.body.issuerCountrySource).toBeUndefined()
  })

  it('accepts additive EMV evidence without changing the legacy boolean', () => {
    const parsed = recordPaymentBodySchema.parse({
      body: {
        ...cardPayment,
        isInternational: true,
        issuerCountryCode: '0840',
        issuerCountrySource: 'EMV_5F28',
      },
    })

    expect(parsed.body.isInternational).toBe(true)
    expect(parsed.body.issuerCountryCode).toBe('0840')
    expect(parsed.body.issuerCountrySource).toBe('EMV_5F28')
  })

  it('discards malformed shadow evidence instead of blocking the payment', () => {
    const parsed = recordPaymentBodySchema.parse({
      body: {
        ...cardPayment,
        issuerCountryCode: 'THIS-IS-NOT-A-COUNTRY-CODE',
        issuerCountrySource: 'SDK_GUESS',
      },
    })

    expect(parsed.body.issuerCountryCode).toBeUndefined()
    expect(parsed.body.issuerCountrySource).toBeUndefined()
  })
})

describe('recordPaymentBodySchema terminalPaymentRequestId length', () => {
  // Real incident (2026-08-07): payments whose terminalPaymentRequestId was 7
  // chars ("qa-qr-1") were rejected 400 → permanently stuck in the offline
  // queue with a banner the cashier can never clear. The field is a POS-echoed
  // correlation key: an unknown/short id is a harmless no-op on the server
  // (closeRowFromPaymentTx findUnique → miss → return), so length must NEVER
  // reject a money recording. Strict validation belongs at request creation,
  // not at recording time.
  it('accepts a short (7-char) terminalPaymentRequestId instead of stranding the payment', () => {
    const parsed = recordPaymentBodySchema.parse({
      body: { ...cardPayment, terminalPaymentRequestId: 'qa-qr-1' },
    })

    expect(parsed.body.terminalPaymentRequestId).toBe('qa-qr-1')
  })

  it('still rejects an empty terminalPaymentRequestId', () => {
    expect(() =>
      recordPaymentBodySchema.parse({
        body: { ...cardPayment, terminalPaymentRequestId: '' },
      }),
    ).toThrow()
  })

  it('still rejects a terminalPaymentRequestId over 64 chars', () => {
    expect(() =>
      recordPaymentBodySchema.parse({
        body: { ...cardPayment, terminalPaymentRequestId: 'x'.repeat(65) },
      }),
    ).toThrow()
  })

  // REGRESSION: idempotencyKey keeps min(8) ON PURPOSE. It is generated by OUR
  // TPV (always a UUID) and its length is load-bearing: it feeds the
  // (venueId, idempotencyKey) dedup that prevents double charges — short keys
  // raise collision risk between DIFFERENT payments. Do not relax it.
  it('still rejects a short idempotencyKey (dedup key stays strict)', () => {
    expect(() =>
      recordPaymentBodySchema.parse({
        body: { ...cardPayment, idempotencyKey: 'short' },
      }),
    ).toThrow()
  })
})

// 🔴 DINERO. Bug REAL encontrado en el D3 (2026-08-17): el POS cobró con un tipo de
// pago del catálogo ("Uber Eats") y el server respondió 400 "Método de pago inválido".
// El cliente manda la REFERENCIA {tenderTypeId, tenderRevision} y OMITE `method` a
// propósito — la semántica de dinero la resuelve el server desde la revisión congelada —
// pero este schema exigía `method` siempre. Resultado: la venta rápida con tipo propio
// era IMPOSIBLE, con el cajero viendo "Error en el pago" y sin salida.
describe('recordPaymentBodySchema — referencia a un tipo de pago del catálogo', () => {
  const tenderPayment = {
    venueId: 'cmn3acoxt000mn227k1vdgj95',
    amount: 5000,
    tip: 0,
    status: 'COMPLETED',
    source: 'AVOQADO_ANDROID',
    splitType: 'FULLPAYMENT',
    staffId: 'staff-1',
    paidProductsId: [],
    tenderTypeId: 'cmn3a6xr8000kn227eg8zeh41',
    tenderRevision: 1,
  }

  it('acepta la referencia SIN method (el server resuelve el método fiscal)', () => {
    const parsed = recordPaymentBodySchema.parse({ body: tenderPayment })

    expect(parsed.body.tenderTypeId).toBe('cmn3a6xr8000kn227eg8zeh41')
    expect(parsed.body.tenderRevision).toBe(1)
    expect(parsed.body.method).toBeUndefined()
  })

  // Sin tender, `method` sigue siendo obligatorio: un cobro sin método ni referencia
  // no tiene forma de saber si entra al cajón.
  it('sigue exigiendo method cuando NO hay referencia a un tipo de pago', () => {
    const { tenderTypeId: _t, tenderRevision: _r, ...sinTender } = tenderPayment
    expect(() => recordPaymentBodySchema.parse({ body: sinTender })).toThrow()
  })

  // Ambigüedad de dinero: si llegan los dos, ¿manda el catálogo o el cliente? Se
  // rechaza en la frontera en vez de elegir en silencio.
  it('rechaza method y tenderTypeId JUNTOS (ambigüedad de dinero)', () => {
    expect(() => recordPaymentBodySchema.parse({ body: { ...tenderPayment, method: 'CASH' } })).toThrow()
  })

  it('rechaza tenderTypeId sin su revisión (una referencia a medias no es verificable)', () => {
    const { tenderRevision: _r, ...sinRevision } = tenderPayment
    expect(() => recordPaymentBodySchema.parse({ body: sinRevision })).toThrow()
  })

  it('rechaza una revisión negativa', () => {
    expect(() => recordPaymentBodySchema.parse({ body: { ...tenderPayment, tenderRevision: -1 } })).toThrow()
  })

  // REGRESIÓN: el refine de merchant lee data.method. Con method ausente no debe
  // reventar (leía `.includes(data.method)` sobre un undefined).
  it('no rompe la regla de merchant cuando method viene ausente', () => {
    const parsed = recordPaymentBodySchema.parse({ body: tenderPayment })
    expect(parsed.body.merchantAccountId).toBeUndefined()
  })
})
