-- AlterTable
ALTER TABLE "public"."PurchaseOrder" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "public"."Venue" ADD COLUMN     "autoReorderConfig" JSONB;
