-- Expand VenueType enum to match BusinessType for multi-vertical support

-- FOOD_SERVICE additions
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'BAKERY';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'CATERING';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'CLOUD_KITCHEN';

-- RETAIL additions
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'JEWELRY';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'CLOTHING';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'ELECTRONICS';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'PHARMACY';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'CONVENIENCE_STORE';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'SUPERMARKET';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'LIQUOR_STORE';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'FURNITURE';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'HARDWARE';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'BOOKSTORE';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'PET_STORE';

-- SERVICES additions
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'SALON';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'FITNESS';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'CLINIC';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'VETERINARY';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'AUTO_SERVICE';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'LAUNDRY';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'REPAIR_SHOP';

-- HOSPITALITY additions
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'HOTEL';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'HOSTEL';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'RESORT';

-- ENTERTAINMENT additions
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'CINEMA';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'ARCADE';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'EVENT_VENUE';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'NIGHTCLUB';
ALTER TYPE "VenueType" ADD VALUE IF NOT EXISTS 'BOWLING';
