import { Prisma } from '@prisma/client'

jest.mock('../../../../src/utils/prismaClient', () => ({
  __esModule: true,
  default: {
    venue: { findUnique: jest.fn() },
    purchaseOrderItem: { findMany: jest.fn() },
  },
}))
jest.mock('../../../../src/services/dashboard/activity-log.service', () => ({
  logAction: jest.fn().mockResolvedValue(undefined),
}))
// supplier.service is imported by the SUT module at load — stub it so import doesn't pull real deps.
jest.mock('../../../../src/services/dashboard/supplier.service', () => ({
  getSupplierRecommendations: jest.fn(),
}))
// basePlan + purchaseOrder are imported at module load; stub to keep import graph light (real impls
// are overridden per-call via injected deps anyway).
jest.mock('../../../../src/services/access/basePlan.service', () => ({ venueHasFeatureAccess: jest.fn(), getVenueBaseTier: jest.fn() }))
jest.mock('../../../../src/services/dashboard/purchaseOrder.service', () => ({ sendPurchaseOrderEmailAsync: jest.fn() }))

import prisma from '../../../../src/utils/prismaClient'
import * as autoReorder from '../../../../src/services/dashboard/autoReorder.service'

const VENUE = 'venue_1'

function suggestion(id: string, urgency: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW', estimatedCost: number, hasSupplier = true) {
  return {
    rawMaterial: { id, name: `rm-${id}`, sku: id, category: 'OTHER', unit: 'KILOGRAM', currentStock: 1, reorderPoint: 5, stockLevel: 0.2 },
    suggestion: {
      urgency,
      suggestedQuantity: 10,
      estimatedCost,
      daysUntilStockout: 2,
      recommendedSupplier: hasSupplier
        ? {
            id: 'sup_1',
            name: 'Sup',
            leadTimeDays: 2,
            pricePerUnit: 1,
            totalCost: estimatedCost,
            estimatedDeliveryDate: new Date(0),
            meetsMinimumOrder: true,
          }
        : null,
      alternativeSuppliers: [],
    },
    analysis: {
      hasSuppliers: hasSupplier,
      supplierCount: hasSupplier ? 1 : 0,
      avgDailyUsage: 1,
      forecastPeriodDays: 30,
      includesSafetyStock: true,
      safetyStockPercentage: 25,
    },
  }
}

// Build an injected-deps object with sensible defaults; override per test.
function makeDeps(overrides: Partial<autoReorder.AutoReorderDeps> = {}): Partial<autoReorder.AutoReorderDeps> {
  return {
    venueHasFeatureAccess: jest.fn().mockResolvedValue(true),
    getVenueBaseTier: jest.fn().mockResolvedValue('PREMIUM'),
    getReorderSuggestions: jest.fn().mockResolvedValue({ suggestions: [] }),
    createPurchaseOrdersFromSuggestions: jest.fn().mockResolvedValue({ success: true, ordersCreated: 0, orders: [] }),
    sendPurchaseOrderEmailAsync: jest.fn().mockResolvedValue(true),
    ...overrides,
  } as Partial<autoReorder.AutoReorderDeps>
}

const ENABLED: autoReorder.AutoReorderConfig = { enabled: true, dailyCapMxn: null, minUrgency: 'LOW' }

describe('runAutoReorderForVenue', () => {
  beforeEach(() => {
    jest.clearAllMocks()
    ;(prisma.purchaseOrderItem.findMany as jest.Mock).mockResolvedValue([])
  })

  it('creates auto-approved POs and emails the supplier for low items', async () => {
    const deps = makeDeps({
      getReorderSuggestions: jest.fn().mockResolvedValue({ suggestions: [suggestion('a', 'HIGH', 100)] }) as any,
      createPurchaseOrdersFromSuggestions: jest
        .fn()
        .mockResolvedValue({ success: true, ordersCreated: 1, orders: [{ id: 'po_1' }] }) as any,
    })
    const res = await autoReorder.runAutoReorderForVenue(VENUE, ENABLED, deps)
    expect(res.ran).toBe(true)
    expect(res.ordersCreated).toBe(1)
    expect(res.emailsSent).toBe(1)
    expect(deps.createPurchaseOrdersFromSuggestions).toHaveBeenCalledWith(VENUE, ['a'], { autoApprove: true, autoGenerated: true })
    expect(deps.sendPurchaseOrderEmailAsync).toHaveBeenCalledWith(VENUE, 'po_1')
  })

  it('skips an item that already has an open PO (dedupe)', async () => {
    ;(prisma.purchaseOrderItem.findMany as jest.Mock).mockResolvedValue([{ rawMaterialId: 'a' }])
    const deps = makeDeps({
      getReorderSuggestions: jest
        .fn()
        .mockResolvedValue({ suggestions: [suggestion('a', 'HIGH', 100), suggestion('b', 'HIGH', 50)] }) as any,
      createPurchaseOrdersFromSuggestions: jest
        .fn()
        .mockResolvedValue({ success: true, ordersCreated: 1, orders: [{ id: 'po_1' }] }) as any,
    })
    const res = await autoReorder.runAutoReorderForVenue(VENUE, ENABLED, deps)
    expect(res.skippedOpenPo).toBe(1)
    expect(deps.createPurchaseOrdersFromSuggestions).toHaveBeenCalledWith(VENUE, ['b'], { autoApprove: true, autoGenerated: true })
  })

  it('respects the daily cap (CRITICAL first, drops what exceeds)', async () => {
    const deps = makeDeps({
      getReorderSuggestions: jest
        .fn()
        .mockResolvedValue({ suggestions: [suggestion('a', 'CRITICAL', 80), suggestion('b', 'HIGH', 50)] }) as any,
      createPurchaseOrdersFromSuggestions: jest
        .fn()
        .mockResolvedValue({ success: true, ordersCreated: 1, orders: [{ id: 'po_1' }] }) as any,
    })
    const res = await autoReorder.runAutoReorderForVenue(VENUE, { enabled: true, dailyCapMxn: 100, minUrgency: 'LOW' }, deps)
    expect(res.skippedCap).toBe(1)
    expect(deps.createPurchaseOrdersFromSuggestions).toHaveBeenCalledWith(VENUE, ['a'], { autoApprove: true, autoGenerated: true })
  })

  it('respects minUrgency', async () => {
    const deps = makeDeps({
      getReorderSuggestions: jest
        .fn()
        .mockResolvedValue({ suggestions: [suggestion('a', 'LOW', 10), suggestion('b', 'CRITICAL', 10)] }) as any,
      createPurchaseOrdersFromSuggestions: jest
        .fn()
        .mockResolvedValue({ success: true, ordersCreated: 1, orders: [{ id: 'po_1' }] }) as any,
    })
    const res = await autoReorder.runAutoReorderForVenue(VENUE, { enabled: true, dailyCapMxn: null, minUrgency: 'HIGH' }, deps)
    expect(res.skippedLowUrgency).toBe(1)
    expect(deps.createPurchaseOrdersFromSuggestions).toHaveBeenCalledWith(VENUE, ['b'], { autoApprove: true, autoGenerated: true })
  })

  it('skips items with no recommended supplier', async () => {
    const deps = makeDeps({
      getReorderSuggestions: jest.fn().mockResolvedValue({ suggestions: [suggestion('a', 'HIGH', 10, false)] }) as any,
    })
    const res = await autoReorder.runAutoReorderForVenue(VENUE, ENABLED, deps)
    expect(res.skippedNoSupplier).toBe(1)
    expect(res.ordersCreated).toBe(0)
    expect(deps.createPurchaseOrdersFromSuggestions).not.toHaveBeenCalled()
  })

  it('does nothing when disabled', async () => {
    const deps = makeDeps()
    const res = await autoReorder.runAutoReorderForVenue(VENUE, { enabled: false, dailyCapMxn: null, minUrgency: 'LOW' }, deps)
    expect(res.ran).toBe(false)
    expect(res.reason).toBe('disabled')
    expect(deps.getReorderSuggestions).not.toHaveBeenCalled()
  })

  it('does nothing when the venue lacks the AUTO_REORDER feature', async () => {
    const deps = makeDeps({ venueHasFeatureAccess: jest.fn().mockResolvedValue(false) as any })
    const res = await autoReorder.runAutoReorderForVenue(VENUE, ENABLED, deps)
    expect(res.ran).toBe(false)
    expect(res.reason).toBe('no_feature')
  })

  it('does nothing for a non-PREMIUM (demo/exempt) venue even if feature access is true', async () => {
    const deps = makeDeps({ getVenueBaseTier: jest.fn().mockResolvedValue(null) as any })
    const res = await autoReorder.runAutoReorderForVenue(VENUE, ENABLED, deps)
    expect(res.ran).toBe(false)
    expect(res.reason).toBe('not_premium')
    expect(deps.getReorderSuggestions).not.toHaveBeenCalled()
  })
})

describe('parseAutoReorderConfig', () => {
  it('defaults to disabled on null', () => {
    expect(autoReorder.parseAutoReorderConfig(null)).toEqual({ enabled: false, dailyCapMxn: null, minUrgency: 'LOW' })
  })
  it('parses a full config', () => {
    expect(autoReorder.parseAutoReorderConfig({ enabled: true, dailyCapMxn: 5000, minUrgency: 'HIGH' } as Prisma.JsonValue)).toEqual({
      enabled: true,
      dailyCapMxn: 5000,
      minUrgency: 'HIGH',
    })
  })
  it('ignores invalid minUrgency / non-positive cap', () => {
    expect(autoReorder.parseAutoReorderConfig({ enabled: true, dailyCapMxn: -3, minUrgency: 'NOPE' } as any)).toEqual({
      enabled: true,
      dailyCapMxn: null,
      minUrgency: 'LOW',
    })
  })
})
