/** Public capability inventory. Display metadata, NOT entitlement or billing authority.
 * Includes base capabilities and assisted modules; presence never makes a capability sellable.
 * Prices and eligible selections belong to a published offer, never to this inventory.
 */
export const FEATURE_CATEGORIES = ['sell', 'customers', 'inventory', 'money', 'team', 'ai', 'custom'] as const
export type FeatureCategoryKey = (typeof FEATURE_CATEGORIES)[number]
export interface FeatureCatalogEntry {
  readonly id: string
  readonly featureCode: string | null
  readonly name: string
  readonly names: Readonly<Record<'es' | 'en' | 'fr', string>>
  readonly description: string
  readonly category: FeatureCategoryKey
  readonly minimumTier: 'FREE' | 'PRO' | 'PREMIUM' | 'ENTERPRISE' | null
  readonly offering: 'INCLUDED' | 'CONFIGURABLE' | 'CONTACT'
  readonly requirement: string | null
}

export const FEATURE_CATALOG: readonly FeatureCatalogEntry[] = Object.freeze(
  (
    [
      {
        id: 'INVENTORY_TRACKING',
        featureCode: 'INVENTORY_TRACKING',
        name: 'Inventario FIFO, recetas y costeo',
        description: 'Controla existencias, recetas, costos y movimientos.',
        category: 'inventory',
        minimumTier: 'PREMIUM',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Inventario FIFO, recetas y costeo',
          en: 'FIFO inventory, recipes and costing',
          fr: 'Inventaire FIFO, recettes et coûts',
        },
      },
      {
        id: 'ADVANCED_REPORTS',
        featureCode: 'ADVANCED_REPORTS',
        name: 'Reportes e histórico completo',
        description: 'Consulta tu histórico y entiende cómo va tu negocio.',
        category: 'money',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Reportes e histórico completo',
          en: 'Reports and full history',
          fr: 'Rapports et historique complet',
        },
      },
      {
        id: 'LOYALTY_PROGRAM',
        featureCode: 'LOYALTY_PROGRAM',
        name: 'Programa de lealtad',
        description: 'Premia a tus clientes y dales motivos para regresar.',
        category: 'customers',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Programa de lealtad',
          en: 'Loyalty program',
          fr: 'Programme de fidélité',
        },
      },
      {
        id: 'RESERVATIONS',
        featureCode: 'RESERVATIONS',
        name: 'Reservas y citas',
        description: 'Organiza citas, reservas y disponibilidad.',
        category: 'sell',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Reservas y citas',
          en: 'Reservations and appointments',
          fr: 'Réservations et rendez-vous',
        },
      },
      {
        id: 'CFDI',
        featureCode: 'CFDI',
        name: 'Facturación CFDI',
        description: 'Emite y administra las facturas de tus clientes.',
        category: 'money',
        minimumTier: 'PREMIUM',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Facturación CFDI',
          en: 'CFDI invoicing',
          fr: 'Facturation CFDI',
        },
      },
      {
        id: 'COMMISSIONS',
        featureCode: 'COMMISSIONS',
        name: 'Comisiones',
        description: 'Calcula y consulta las comisiones de tu equipo.',
        category: 'team',
        minimumTier: 'PREMIUM',
        offering: 'CONFIGURABLE',
        requirement: 'Requiere habilitar el módulo de comisiones.',
        names: {
          es: 'Comisiones',
          en: 'Commissions',
          fr: 'Commissions',
        },
      },
      {
        id: 'BASE_POS',
        featureCode: null,
        name: 'Cobra con tarjeta (TPV)',
        description: 'Registra ventas y cobra con tu terminal habilitada.',
        category: 'sell',
        minimumTier: 'FREE',
        offering: 'INCLUDED',
        requirement: null,
        names: {
          es: 'Cobra con tarjeta (TPV)',
          en: 'Card payments (terminal)',
          fr: 'Paiement par carte (terminal)',
        },
      },
      {
        id: 'BASE_MENUORDERS',
        featureCode: null,
        name: 'Menú y órdenes',
        description: 'Organiza tu catálogo y lleva tus órdenes.',
        category: 'sell',
        minimumTier: 'FREE',
        offering: 'INCLUDED',
        requirement: null,
        names: {
          es: 'Menú y órdenes',
          en: 'Menu and orders',
          fr: 'Menu et commandes',
        },
      },
      {
        id: 'TABLE_SERVICE',
        featureCode: 'TABLE_SERVICE',
        name: 'Servicio de mesas',
        description: 'Organiza mesas y atiende cada cuenta.',
        category: 'sell',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Servicio de mesas',
          en: 'Table service',
          fr: 'Service à table',
        },
      },
      {
        id: 'ONLINE_ORDERING',
        featureCode: 'ONLINE_ORDERING',
        name: 'Pedidos en línea',
        description: 'Recibe pedidos desde tus canales en línea.',
        category: 'sell',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Pedidos en línea',
          en: 'Online ordering',
          fr: 'Commande en ligne',
        },
      },
      {
        id: 'UPSELL',
        featureCode: 'UPSELL',
        name: 'Sugerencias «¿algo más?» al cobrar',
        description: 'Sugiere un complemento al momento de cobrar.',
        category: 'sell',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Sugerencias «¿algo más?» al cobrar',
          en: 'Upsell prompts at checkout',
          fr: "Suggestions à l'encaissement",
        },
      },
      {
        id: 'UPSELL_AI',
        featureCode: 'UPSELL_AI',
        name: 'Sugerencias escritas con IA',
        description: 'Crea sugerencias de venta con ayuda de IA.',
        category: 'sell',
        minimumTier: 'PREMIUM',
        offering: 'CONFIGURABLE',
        requirement: 'Requiere el motor de sugerencias de venta.',
        names: {
          es: 'Sugerencias escritas con IA',
          en: 'AI-written suggestions',
          fr: 'Suggestions rédigées par IA',
        },
      },
      {
        id: 'DELIVERY_CHANNELS',
        featureCode: 'DELIVERY_CHANNELS',
        name: 'Delivery (Uber Eats, Rappi, DiDi)',
        description: 'Gestiona pedidos de tus canales de entrega.',
        category: 'sell',
        minimumTier: 'PREMIUM',
        offering: 'CONFIGURABLE',
        requirement: 'Requiere conectar los canales de entrega.',
        names: {
          es: 'Delivery (Uber Eats, Rappi, DiDi)',
          en: 'Delivery (Uber Eats, Rappi, DiDi)',
          fr: 'Livraison (Uber Eats, Rappi, DiDi)',
        },
      },
      {
        id: 'MERCHANT_ROUTING_RULES',
        featureCode: 'MERCHANT_ROUTING_RULES',
        name: 'Reglas de cobro por comercio',
        description: 'Define qué cuenta de cobro usar en cada caso.',
        category: 'sell',
        minimumTier: 'PREMIUM',
        offering: 'CONFIGURABLE',
        requirement: 'Requiere cuentas de cobro configuradas.',
        names: {
          es: 'Reglas de cobro por comercio',
          en: 'Payment routing rules',
          fr: "Règles d'encaissement par commerçant",
        },
      },
      {
        id: 'REFERRAL_PROGRAM',
        featureCode: 'REFERRAL_PROGRAM',
        name: 'Referidos',
        description: 'Recompensa a quienes recomiendan tu negocio.',
        category: 'customers',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Referidos',
          en: 'Referrals',
          fr: 'Parrainage',
        },
      },
      {
        id: 'PROMOTIONS',
        featureCode: 'PROMOTIONS',
        name: 'Promociones',
        description: 'Crea descuentos, cupones y paquetes promocionales.',
        category: 'customers',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Promociones',
          en: 'Promotions',
          fr: 'Promotions',
        },
      },
      {
        id: 'CUSTOMER_CAMPAIGNS',
        featureCode: 'CUSTOMER_CAMPAIGNS',
        name: 'Campañas por correo a tus clientes',
        description: 'Envía promociones y mensajes a tus clientes.',
        category: 'customers',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Campañas por correo a tus clientes',
          en: 'Email campaigns to your customers',
          fr: 'Campagnes e-mail à vos clients',
        },
      },
      {
        id: 'GOOGLE_REVIEW_REDIRECT',
        featureCode: 'GOOGLE_REVIEW_REDIRECT',
        name: 'Reseñas en Google',
        description: 'Invita a tus clientes a dejar una reseña en Google.',
        category: 'customers',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Reseñas en Google',
          en: 'Google reviews',
          fr: 'Avis Google',
        },
      },
      {
        id: 'BASE_INVENTORYBASIC',
        featureCode: null,
        name: 'Inventario básico',
        description: 'Lleva el control básico de tus productos.',
        category: 'inventory',
        minimumTier: 'FREE',
        offering: 'INCLUDED',
        requirement: null,
        names: {
          es: 'Inventario básico',
          en: 'Basic inventory',
          fr: 'Inventaire de base',
        },
      },
      {
        id: 'AUTO_REORDER',
        featureCode: 'AUTO_REORDER',
        name: 'Reorden automático',
        description: 'Prepara la reposición antes de quedarte sin stock.',
        category: 'inventory',
        minimumTier: 'PREMIUM',
        offering: 'CONFIGURABLE',
        requirement: 'Requiere inventario configurado.',
        names: {
          es: 'Reorden automático',
          en: 'Auto-reorder',
          fr: 'Réapprovisionnement automatique',
        },
      },
      {
        id: 'SERIALIZED_INVENTORY',
        featureCode: 'SERIALIZED_INVENTORY',
        name: 'Inventario por número de serie',
        description: 'Identifica y sigue cada unidad por su número de serie.',
        category: 'inventory',
        minimumTier: 'PREMIUM',
        offering: 'CONFIGURABLE',
        requirement: 'Requiere habilitar el módulo de inventario por número de serie.',
        names: {
          es: 'Inventario por número de serie',
          en: 'Serialized inventory',
          fr: 'Inventaire par numéro de série',
        },
      },
      {
        id: 'PRICE_LABELS',
        featureCode: 'PRICE_LABELS',
        name: 'Etiquetas de precios',
        description: 'Imprime etiquetas para los productos de tu negocio desde el POS.',
        category: 'inventory',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: 'Requiere una impresora compatible con el POS.',
        names: { es: 'Etiquetas de precios', en: 'Price labels', fr: 'Étiquettes de prix' },
      },
      {
        id: 'SCALE_INTEGRATION',
        featureCode: 'SCALE_INTEGRATION',
        name: 'Báscula conectada',
        description: 'Conecta una báscula compatible a tu operación.',
        category: 'inventory',
        minimumTier: 'PREMIUM',
        offering: 'CONFIGURABLE',
        requirement: 'Requiere báscula y conexión compatibles.',
        names: {
          es: 'Báscula conectada',
          en: 'Connected scale',
          fr: 'Balance connectée',
        },
      },
      {
        id: 'BASE_DAILYREPORTS',
        featureCode: null,
        name: 'Reportes del día',
        description: 'Consulta las ventas y resultados del día.',
        category: 'money',
        minimumTier: 'FREE',
        offering: 'INCLUDED',
        requirement: null,
        names: {
          es: 'Reportes del día',
          en: 'Daily reports',
          fr: 'Rapports du jour',
        },
      },
      {
        id: 'CASH_RECONCILIATION',
        featureCode: 'CASH_RECONCILIATION',
        name: 'Arqueo de caja por turno',
        description: 'Compara lo contado con lo esperado al cerrar caja.',
        category: 'money',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Arqueo de caja por turno',
          en: 'Cash drawer count per shift',
          fr: 'Comptage de caisse par service',
        },
      },
      {
        id: 'BANK_RECONCILIATION',
        featureCode: 'BANK_RECONCILIATION',
        name: 'Conciliación bancaria',
        description: 'Concilia tus movimientos y cuentas bancarias.',
        category: 'money',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Conciliación bancaria',
          en: 'Bank reconciliation',
          fr: 'Rapprochement bancaire',
        },
      },
      {
        id: 'AVAILABLE_BALANCE',
        featureCode: 'AVAILABLE_BALANCE',
        name: 'Saldo disponible',
        description: 'Consulta tu saldo y las liquidaciones pendientes.',
        category: 'money',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Saldo disponible',
          en: 'Available balance',
          fr: 'Solde disponible',
        },
      },
      {
        id: 'BANKING_HUB',
        featureCode: 'BANKING_HUB',
        name: 'Centro bancario',
        description: 'Gestiona movimientos, beneficiarios y transferencias.',
        category: 'money',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: 'Requiere activación bancaria y validación del negocio.',
        names: {
          es: 'Centro bancario',
          en: 'Banking hub',
          fr: 'Centre bancaire',
        },
      },
      {
        id: 'TRANSACTION_EXPORT',
        featureCode: 'TRANSACTION_EXPORT',
        name: 'Exportar transacciones',
        description: 'Descarga el detalle de tus transacciones.',
        category: 'money',
        minimumTier: 'PREMIUM',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Exportar transacciones',
          en: 'Transaction export',
          fr: 'Export des transactions',
        },
      },
      {
        id: 'VENUE_AUDIT_LOG',
        featureCode: 'VENUE_AUDIT_LOG',
        name: 'Bitácora de actividad',
        description: 'Consulta quién hizo cada cambio en tu negocio.',
        category: 'team',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Bitácora de actividad',
          en: 'Activity log',
          fr: "Journal d'activité",
        },
      },
      {
        id: 'ATTENDANCE_TRACKING',
        featureCode: 'ATTENDANCE_TRACKING',
        name: 'Checador de asistencia',
        description: 'Registra entradas y salidas de tu equipo.',
        category: 'team',
        minimumTier: 'PREMIUM',
        offering: 'CONFIGURABLE',
        requirement: 'Requiere habilitar el módulo de asistencia.',
        names: {
          es: 'Checador de asistencia',
          en: 'Attendance clock',
          fr: 'Pointage',
        },
      },
      {
        id: 'CHATBOT',
        featureCode: 'CHATBOT',
        name: 'Chatbot',
        description: 'Resuelve dudas con el chatbot incluido.',
        category: 'ai',
        minimumTier: 'FREE',
        offering: 'INCLUDED',
        requirement: null,
        names: {
          es: 'Chatbot',
          en: 'Chatbot',
          fr: 'Chatbot',
        },
      },
      {
        id: 'AI_ASSISTANT_BUBBLE',
        featureCode: 'AI_ASSISTANT_BUBBLE',
        name: 'Asistente IA y MCP',
        description: 'Consulta y gestiona tu negocio con ayuda de IA.',
        category: 'ai',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Asistente IA y MCP',
          en: 'AI assistant and MCP',
          fr: 'Assistant IA et MCP',
        },
      },
      {
        id: 'OFFLINE_LAN_HUB',
        featureCode: 'OFFLINE_LAN_HUB',
        name: 'Aparatos coordinados sin internet',
        description: 'Coordina aparatos compatibles por tu red local.',
        category: 'ai',
        minimumTier: 'PREMIUM',
        offering: 'CONFIGURABLE',
        requirement: 'Requiere dispositivos compatibles conectados a la misma red local.',
        names: {
          es: 'Aparatos coordinados sin internet',
          en: 'Devices in sync without internet',
          fr: 'Appareils synchronisés sans internet',
        },
      },
      {
        id: 'WHITE_LABEL_DASHBOARD',
        featureCode: 'WHITE_LABEL_DASHBOARD',
        name: 'Marca propia (white-label)',
        description: 'Experiencia con marca propia y módulos especializados para tu operación.',
        category: 'custom',
        minimumTier: 'ENTERPRISE',
        offering: 'CONTACT',
        requirement: null,
        names: {
          es: 'Marca propia (white-label)',
          en: 'White-label',
          fr: 'Marque propre',
        },
      },
      {
        id: 'ENTERPRISE_API',
        featureCode: null,
        name: 'API e integraciones',
        description: 'Integraciones acordadas para las necesidades de tu organización.',
        category: 'custom',
        minimumTier: 'ENTERPRISE',
        offering: 'CONTACT',
        requirement: null,
        names: {
          es: 'API e integraciones',
          en: 'API and integrations',
          fr: 'API et intégrations',
        },
      },
      {
        id: 'ENTERPRISE_SUPPORT',
        featureCode: null,
        name: 'SLA y soporte dedicado',
        description: 'Condiciones de servicio y acompañamiento acordados con tu organización.',
        category: 'custom',
        minimumTier: 'ENTERPRISE',
        offering: 'CONTACT',
        requirement: null,
        names: {
          es: 'SLA y soporte dedicado',
          en: 'SLA and dedicated support',
          fr: 'SLA et assistance dédiée',
        },
      },
      {
        id: 'AREA_TICKETS',
        featureCode: 'AREA_TICKETS',
        name: 'Vales por área',
        description: 'Organiza el surtido y cobro por áreas.',
        category: 'sell',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Vales por área',
          en: 'Area tickets',
          fr: 'Bons par zone',
        },
      },
      {
        id: 'VARIABLE_WEIGHT_BARCODE',
        featureCode: 'VARIABLE_WEIGHT_BARCODE',
        name: 'Códigos de peso variable',
        description: 'Lee códigos de productos pesados desde una báscula compatible.',
        category: 'sell',
        minimumTier: 'PRO',
        offering: 'CONFIGURABLE',
        requirement: null,
        names: {
          es: 'Códigos de peso variable',
          en: 'Variable-weight barcodes',
          fr: 'Codes-barres à poids variable',
        },
      },
      {
        id: 'MASTER_CATALOG',
        featureCode: 'MASTER_CATALOG',
        name: 'Catálogo maestro',
        description: 'Catálogo central para tu organización. Requiere habilitación de Avoqado; no tiene precio individual definido.',
        category: 'custom',
        minimumTier: null,
        offering: 'CONTACT',
        requirement: null,
        names: {
          es: 'Catálogo maestro',
          en: 'Master catalog',
          fr: 'Catalogue central',
        },
      },
    ] as FeatureCatalogEntry[]
  ).map(entry => Object.freeze({ ...entry, names: Object.freeze(entry.names) })),
)
