import { z } from 'zod'

// ==========================================
// ORG TERMINAL MANAGEMENT SCHEMAS
// ==========================================

// IDs are validated for existence by the service layer (Prisma findUnique /
// findMany), not by regex here. Strict cuid validation rejects legitimate IDs
// generated by older Prisma versions or alternative generators. The service
// returns a proper 404/403 if the ID doesn't resolve.
const OrgIdParams = z.object({
  orgId: z.string().min(1, 'ID de organización requerido'),
})

const OrgTerminalParams = z.object({
  orgId: z.string().min(1, 'ID de organización requerido'),
  terminalId: z.string().min(1, 'ID de terminal requerido'),
})

// Commands allowed at org level — must match ORG_ALLOWED_COMMANDS in orgTerminals.service.ts
const OrgAllowedCommands = [
  'LOCK',
  'UNLOCK',
  'MAINTENANCE_MODE',
  'EXIT_MAINTENANCE',
  'RESTART',
  'CLEAR_CACHE',
  'EXPORT_LOGS',
  'REMOTE_ACTIVATE',
  'FACTORY_RESET',
  'SYNC_DATA',
  'REFRESH_MENU',
  'FORCE_UPDATE',
  'REQUEST_UPDATE',
  'UPDATE_CONFIG',
  'UPDATE_MERCHANT',
] as const

/**
 * GET /:orgId/terminals/:terminalId
 */
export const GetOrgTerminalSchema = z.object({
  params: OrgTerminalParams,
})

/**
 * POST /:orgId/terminals
 */
export const CreateOrgTerminalSchema = z.object({
  body: z.object({
    venueId: z.string().min(1, 'ID de sucursal requerido'),
    serialNumber: z.string().min(1, 'El número de serie es requerido'),
    name: z.string().min(1, 'El nombre es requerido').max(255, 'El nombre no puede exceder 255 caracteres'),
    type: z.enum(['TPV_ANDROID', 'TPV_IOS', 'PRINTER_RECEIPT', 'PRINTER_KITCHEN', 'KDS'], {
      errorMap: () => ({ message: 'Tipo de terminal inválido' }),
    }),
    brand: z.string().max(100).optional(),
    model: z.string().max(100).optional(),
    assignedMerchantIds: z.array(z.string().min(1)).optional(),
    generateActivationCode: z.boolean().optional(),
  }),
  params: OrgIdParams,
})
export type CreateOrgTerminalDto = z.infer<typeof CreateOrgTerminalSchema>['body']

/**
 * PATCH /:orgId/terminals/:terminalId
 */
export const UpdateOrgTerminalSchema = z.object({
  body: z.object({
    name: z.string().min(1, 'El nombre es requerido').max(255, 'El nombre no puede exceder 255 caracteres').optional(),
    status: z
      .enum(['ACTIVE', 'INACTIVE', 'MAINTENANCE', 'RETIRED'], {
        errorMap: () => ({ message: 'Estado inválido' }),
      })
      .optional(),
    brand: z.string().max(100).optional(),
    model: z.string().max(100).optional(),
    assignedMerchantIds: z.array(z.string().min(1)).optional(),
  }),
  params: OrgTerminalParams,
})
export type UpdateOrgTerminalDto = z.infer<typeof UpdateOrgTerminalSchema>['body']

/**
 * DELETE /:orgId/terminals/:terminalId
 */
export const DeleteOrgTerminalSchema = z.object({
  params: OrgTerminalParams,
})

/**
 * POST /:orgId/terminals/:terminalId/generate-activation-code
 */
export const GenerateActivationCodeSchema = z.object({
  params: OrgTerminalParams,
})

/**
 * POST /:orgId/terminals/:terminalId/remote-activate
 */
export const RemoteActivateSchema = z.object({
  params: OrgTerminalParams,
})

/**
 * POST /:orgId/terminals/:terminalId/command
 */
export const SendOrgCommandSchema = z.object({
  body: z.object({
    command: z.enum(OrgAllowedCommands, {
      errorMap: () => ({
        message: `Comando no permitido. Comandos válidos: ${OrgAllowedCommands.join(', ')}`,
      }),
    }),
    // Target app version for REQUEST_UPDATE. When provided, the TPV is asked to
    // update to this specific AppUpdate.versionCode (it shows the operator a
    // confirmation dialog). Optional — omitted means "latest" (current TPV
    // behavior). Ignored for non-update commands.
    versionCode: z.number({ invalid_type_error: 'versionCode debe ser numérico' }).int().positive().optional(),
  }),
  params: OrgTerminalParams,
})
export type SendOrgCommandDto = z.infer<typeof SendOrgCommandSchema>['body']

/**
 * POST /:orgId/terminals/bulk-command
 * Run one safe command across many terminals.
 *
 * terminalIds: not regex-validated here — the service does a batched DB lookup
 * against the org's venues and returns a per-row { success, error } for any
 * id that doesn't belong. Strict CUID validation at the schema layer rejects
 * legitimate IDs whose format predates the current generator.
 */
const SafeBulkCommands = ['RESTART', 'SYNC_DATA', 'REFRESH_MENU', 'FORCE_UPDATE', 'LOCK', 'UNLOCK'] as const
export const BulkCommandSchema = z.object({
  body: z.object({
    terminalIds: z
      .array(z.string().min(1, 'ID de terminal vacío'))
      .min(1, 'Selecciona al menos una terminal')
      .max(100, 'Máximo 100 terminales por solicitud'),
    command: z.enum(SafeBulkCommands, {
      errorMap: () => ({ message: `Comando no permitido para ejecución masiva. Comandos válidos: ${SafeBulkCommands.join(', ')}` }),
    }),
  }),
  params: OrgIdParams,
})
export type BulkCommandDto = z.infer<typeof BulkCommandSchema>['body']

/**
 * PUT /:orgId/terminals/:terminalId/merchants
 */
export const AssignMerchantsSchema = z.object({
  body: z.object({
    merchantIds: z.array(z.string().min(1, 'ID de comercio vacío')),
  }),
  params: OrgTerminalParams,
})
export type AssignMerchantsDto = z.infer<typeof AssignMerchantsSchema>['body']

/**
 * GET /:orgId/merchant-accounts
 */
export const GetOrgMerchantAccountsSchema = z.object({
  params: OrgIdParams,
})

// ==========================================
// ORG TERMINAL MIGRATION SCHEMAS
// ==========================================
//
// IDs (orgId, terminalId, toVenueId, merchantIds) are NOT regex/cuid validated —
// they may be cuid OR uuid depending on the generator that created them. The
// service layer + ownership validators resolve them against the DB and return a
// proper 404/403 if they don't belong to the org. Shape-only checks here.

/**
 * POST /:orgId/terminals/:terminalId/migrate-preflight
 * Body: { toVenueId }
 */
export const orgMigratePreflightSchema = z.object({
  body: z.object({
    toVenueId: z.string().min(1, 'ID de sucursal destino requerido'),
  }),
  params: OrgTerminalParams,
})
export type OrgMigratePreflightDto = z.infer<typeof orgMigratePreflightSchema>['body']

/**
 * POST /:orgId/terminals/:terminalId/migrate-execute
 * Body: { toVenueId, assignedMerchantIds? }
 */
export const orgMigrateExecuteSchema = z.object({
  body: z.object({
    toVenueId: z.string().min(1, 'ID de sucursal destino requerido'),
    assignedMerchantIds: z.array(z.string().min(1, 'ID de comercio vacío')).optional(),
  }),
  params: OrgTerminalParams,
})
export type OrgMigrateExecuteDto = z.infer<typeof orgMigrateExecuteSchema>['body']

/**
 * GET /:orgId/terminals/:terminalId/migrate-status
 * Query: { commandId }
 */
export const orgMigrateStatusSchema = z.object({
  query: z.object({
    commandId: z.string().min(1, 'ID de comando requerido'),
  }),
  params: OrgTerminalParams,
})

/**
 * POST /:orgId/terminals/:terminalId/migrate-cancel
 * Params only.
 */
export const orgMigrateCancelSchema = z.object({
  params: OrgTerminalParams,
})
