/**
 * seed-la-ribera-demo.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Creates the RESTAURANT demo venue "La Ribera — Cocina Mexicana"
 * (slug: la-ribera-demo) for the hands-on prospect demo (grupo 3 sucursales +
 * CEDIS, reunión 2026-07-23). Pattern: scripts/seed-avoqado-fitness-demo.ts
 * (additive, slug-guarded, --teardown) + scripts/seed-demo-venues.ts (typed
 * catalog + history) + onboarding/demoSeed.service.ts (recipes/tables/orders).
 *
 * What it seeds (all realistic, Spanish, restaurant-grade):
 *   • Menú: 6 categorías + ~34 productos (incl. "Charcutería & Granel" con
 *     productos por kg listos para el MVP de báscula) + 5 grupos de
 *     modificadores (extras ligados a materia prima → descuentan inventario).
 *   • Recetas (Recipe + RecipeLine) sobre 19 materias primas con lotes FIFO,
 *     costos, caducidades y 2 insumos deliberadamente BAJO reorder point.
 *   • Meseros con PIN (StaffVenue.pin) + logins demo existentes enlazados.
 *   • 3 áreas / 22 mesas con posiciones de plano.
 *   • Historia: ~21 días de shifts CERRADOS + órdenes DINE_IN/TAKEOUT con
 *     propinas, modificadores, clientes, reviews y mix de pago (cash/tarjeta).
 *   • Historia CEDIS: proveedor interno "CEDIS Central del Grupo" + 2 externos,
 *     SupplierPricing, 2 POs RECIBIDAS (batches FIFO ligados), 1 SENT,
 *     1 PENDING_APPROVAL autoGenerated=true (money shot del auto-reorden).
 *   • Features: PLAN_PREMIUM (base tier real → auto-reorder corre), AUTO_REORDER,
 *     INVENTORY_TRACKING, CHATBOT, etc. + autoReorderConfig habilitado.
 *
 * SAFETY
 *   - Additive only: new venue subtree; never touches avoqado-full/fitness.
 *   - Aborts if slug exists (unless --force = teardown + reseed).
 *   - Reversible: --teardown deletes the venue subtree (FK-safe explicit order).
 *   - Prod guard: refuses a render.com DATABASE_URL without --prod.
 *
 * RUN (local av-db-25):
 *   npx tsx scripts/seed-la-ribera-demo.ts
 * RUN (PROD Render):
 *   DATABASE_URL="$RENDER_DATABASE_URL" npx tsx scripts/seed-la-ribera-demo.ts --prod
 * TEARDOWN:
 *   [DATABASE_URL=…] npx tsx scripts/seed-la-ribera-demo.ts --teardown [--prod]
 */
import {
  BatchStatus,
  InventoryMethod,
  OrderStatus,
  OrderType,
  OrderSource,
  PaymentMethod,
  PaymentStatus,
  ProductType,
  PurchaseOrderStatus,
  PurchaseOrderItemStatus,
  RawMaterialCategory,
  ReservationChannel,
  ReservationStatus,
  ReviewSource,
  ShiftStatus,
  StaffRole,
  Unit,
  UnitType,
} from '@prisma/client'
import { addDays, addMinutes, subDays, format } from 'date-fns'
import { formatInTimeZone, fromZonedTime } from 'date-fns-tz'
import { randomBytes } from 'crypto'

import prisma from '../src/utils/prismaClient'
import logger from '../src/config/logger'
import { saveVenueFeatures } from '../src/services/dashboard/feature.service'

// ─── Constants ───────────────────────────────────────────────────────────────
const NEW_SLUG = 'la-ribera-demo'
const NEW_NAME = 'La Ribera — Cocina Mexicana'
const TZ = 'America/Mexico_City'
const ACCENT = '#7ADD2C'
const HISTORY_DAYS = 21 // yesterday .. 21 days back (today stays clean for live demo)

// PLAN_PREMIUM: real base tier (auto-reorder's run gate checks getVenueBaseTier === PREMIUM).
const FEATURE_CODES = [
  'PLAN_PREMIUM',
  'AUTO_REORDER',
  'INVENTORY_TRACKING',
  'ADVANCED_ANALYTICS',
  'ADVANCED_REPORTS',
  'AI_ASSISTANT_BUBBLE',
  'AVAILABLE_BALANCE',
  'CHATBOT',
  'LOYALTY_PROGRAM',
  'ONLINE_ORDERING',
  'RESERVATIONS',
]

// Known demo logins (resolved by email at runtime — portable local/prod).
const DEMO_LOGINS: Array<{ email: string; role: StaffRole }> = [
  { email: 'superadmin@superadmin.com', role: StaffRole.SUPERADMIN },
  { email: 'owner@owner.com', role: StaffRole.OWNER },
  { email: 'admin@admin.com', role: StaffRole.ADMIN },
  { email: 'manager@manager.com', role: StaffRole.MANAGER },
  { email: 'cashier@cashier.com', role: StaffRole.CASHIER },
]

const WAITERS = [
  { first: 'Luis', last: 'Hernández', pin: '1234', role: StaffRole.WAITER },
  { first: 'Fernanda', last: 'Ortiz', pin: '2345', role: StaffRole.WAITER },
  { first: 'Diego', last: 'Ramos', pin: '3456', role: StaffRole.WAITER },
  { first: 'Valeria', last: 'Cruz', pin: '4567', role: StaffRole.WAITER },
  { first: 'Ramón', last: 'Aguilar', pin: '8888', role: StaffRole.KITCHEN },
]

// ─── Raw materials (ingredientes) ────────────────────────────────────────────
type RM = {
  key: string
  name: string
  sku: string
  category: RawMaterialCategory
  unit: Unit
  unitType: UnitType
  cost: number // per unit (MXN)
  stock: number // current
  min: number
  reorder: number
  max: number
  perishable?: boolean
  shelfLifeDays?: number
  meat?: boolean // true → supplied by Carnes Selectas; else CEDIS
}

const RAW_MATERIALS: RM[] = [
  // ⚠️ tortilla + aguacate quedan BAJO su reorder point a propósito (demo de alertas + auto-reorden)
  {
    key: 'tortilla',
    name: 'Tortilla de maíz',
    sku: 'RM-TOR',
    category: RawMaterialCategory.GRAINS,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 22,
    stock: 9.2,
    min: 7,
    reorder: 10,
    max: 30,
    perishable: true,
    shelfLifeDays: 4,
  },
  {
    key: 'aguacate',
    name: 'Aguacate Hass',
    sku: 'RM-AGU',
    category: RawMaterialCategory.FRUITS,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 92,
    stock: 5.4,
    min: 4,
    reorder: 6,
    max: 18,
    perishable: true,
    shelfLifeDays: 5,
  },
  {
    key: 'pollo',
    name: 'Pechuga de pollo',
    sku: 'RM-POL',
    category: RawMaterialCategory.POULTRY,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 98,
    stock: 24,
    min: 6,
    reorder: 8,
    max: 35,
    perishable: true,
    shelfLifeDays: 4,
    meat: true,
  },
  {
    key: 'arrachera',
    name: 'Arrachera marinada',
    sku: 'RM-ARR',
    category: RawMaterialCategory.MEAT,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 262,
    stock: 12,
    min: 3.5,
    reorder: 5,
    max: 20,
    perishable: true,
    shelfLifeDays: 5,
    meat: true,
  },
  {
    key: 'bistec',
    name: 'Bistec de res',
    sku: 'RM-BIS',
    category: RawMaterialCategory.MEAT,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 145,
    stock: 9,
    min: 3,
    reorder: 4,
    max: 16,
    perishable: true,
    shelfLifeDays: 5,
    meat: true,
  },
  {
    key: 'pastor',
    name: 'Cerdo adobado al pastor',
    sku: 'RM-PAS',
    category: RawMaterialCategory.MEAT,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 118,
    stock: 14,
    min: 4,
    reorder: 6,
    max: 22,
    perishable: true,
    shelfLifeDays: 5,
    meat: true,
  },
  {
    key: 'suadero',
    name: 'Suadero',
    sku: 'RM-SUA',
    category: RawMaterialCategory.MEAT,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 132,
    stock: 8,
    min: 2.5,
    reorder: 3.5,
    max: 14,
    perishable: true,
    shelfLifeDays: 5,
    meat: true,
  },
  {
    key: 'queso',
    name: 'Queso Oaxaca',
    sku: 'RM-QUE',
    category: RawMaterialCategory.CHEESE,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 148,
    stock: 10.5,
    min: 3,
    reorder: 4,
    max: 15,
    perishable: true,
    shelfLifeDays: 10,
  },
  {
    key: 'jitomate',
    name: 'Jitomate saladet',
    sku: 'RM-JIT',
    category: RawMaterialCategory.VEGETABLES,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 28,
    stock: 16,
    min: 4,
    reorder: 6,
    max: 25,
    perishable: true,
    shelfLifeDays: 6,
  },
  {
    key: 'cebolla',
    name: 'Cebolla blanca',
    sku: 'RM-CEB',
    category: RawMaterialCategory.VEGETABLES,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 24,
    stock: 12,
    min: 3.5,
    reorder: 5,
    max: 20,
    perishable: true,
    shelfLifeDays: 12,
  },
  {
    key: 'frijol',
    name: 'Frijol negro',
    sku: 'RM-FRI',
    category: RawMaterialCategory.BEANS,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 38,
    stock: 14,
    min: 3.5,
    reorder: 5,
    max: 22,
  },
  {
    key: 'salsaverde',
    name: 'Salsa verde (preparada)',
    sku: 'RM-SAV',
    category: RawMaterialCategory.OTHER,
    unit: Unit.LITER,
    unitType: UnitType.VOLUME,
    cost: 36,
    stock: 10,
    min: 3,
    reorder: 4,
    max: 16,
    perishable: true,
    shelfLifeDays: 6,
  },
  {
    key: 'salsaroja',
    name: 'Salsa roja (preparada)',
    sku: 'RM-SAR',
    category: RawMaterialCategory.OTHER,
    unit: Unit.LITER,
    unitType: UnitType.VOLUME,
    cost: 36,
    stock: 9,
    min: 3,
    reorder: 4,
    max: 16,
    perishable: true,
    shelfLifeDays: 6,
  },
  {
    key: 'crema',
    name: 'Crema ácida',
    sku: 'RM-CRE',
    category: RawMaterialCategory.DAIRY,
    unit: Unit.LITER,
    unitType: UnitType.VOLUME,
    cost: 62,
    stock: 6.5,
    min: 2,
    reorder: 2.5,
    max: 10,
    perishable: true,
    shelfLifeDays: 10,
  },
  {
    key: 'huevo',
    name: 'Huevo',
    sku: 'RM-HUE',
    category: RawMaterialCategory.EGGS,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 48,
    stock: 10,
    min: 3,
    reorder: 4,
    max: 16,
    perishable: true,
    shelfLifeDays: 15,
  },
  {
    key: 'cafe',
    name: 'Café molido de olla',
    sku: 'RM-CAF',
    category: RawMaterialCategory.OTHER,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 215,
    stock: 4.2,
    min: 1,
    reorder: 1.5,
    max: 8,
  },
  {
    key: 'masa',
    name: 'Mezcla para hotcakes',
    sku: 'RM-MAS',
    category: RawMaterialCategory.GRAINS,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 55,
    stock: 5,
    min: 1.5,
    reorder: 2,
    max: 10,
  },
  {
    key: 'bolillo',
    name: 'Pan bolillo',
    sku: 'RM-BOL',
    category: RawMaterialCategory.BREAD,
    unit: Unit.PIECE,
    unitType: UnitType.COUNT,
    cost: 4.5,
    stock: 38,
    min: 10,
    reorder: 15,
    max: 80,
    perishable: true,
    shelfLifeDays: 2,
  },
  {
    key: 'pina',
    name: 'Piña',
    sku: 'RM-PIN',
    category: RawMaterialCategory.FRUITS,
    unit: Unit.KILOGRAM,
    unitType: UnitType.WEIGHT,
    cost: 30,
    stock: 6,
    min: 2,
    reorder: 2.5,
    max: 10,
    perishable: true,
    shelfLifeDays: 6,
  },
]

// ─── Modifier groups ─────────────────────────────────────────────────────────
type ModDef = { name: string; price: number; rmKey?: string; qty?: number; unit?: Unit }
type GroupDef = { key: string; name: string; required: boolean; allowMultiple: boolean; min: number; max: number | null; mods: ModDef[] }

const MODIFIER_GROUPS: GroupDef[] = [
  {
    key: 'termino',
    name: 'Término de la carne',
    required: true,
    allowMultiple: false,
    min: 1,
    max: 1,
    mods: [
      { name: 'Término 1/2', price: 0 },
      { name: 'Término 3/4', price: 0 },
      { name: 'Bien cocido', price: 0 },
    ],
  },
  {
    key: 'tortilla',
    name: 'Tipo de tortilla',
    required: true,
    allowMultiple: false,
    min: 1,
    max: 1,
    mods: [
      { name: 'Maíz', price: 0 },
      { name: 'Harina', price: 0 },
    ],
  },
  {
    key: 'huevos',
    name: 'Preparación de los huevos',
    required: true,
    allowMultiple: false,
    min: 1,
    max: 1,
    mods: [
      { name: 'Revueltos', price: 0 },
      { name: 'Estrellados', price: 0 },
      { name: 'A la mexicana', price: 0 },
      { name: 'Con jamón', price: 12 },
    ],
  },
  {
    key: 'extras',
    name: 'Extras',
    required: false,
    allowMultiple: true,
    min: 0,
    max: 4,
    mods: [
      { name: 'Extra queso', price: 22, rmKey: 'queso', qty: 0.05, unit: Unit.KILOGRAM },
      { name: 'Extra aguacate', price: 26, rmKey: 'aguacate', qty: 0.1, unit: Unit.KILOGRAM },
      { name: 'Extra tortillas', price: 15, rmKey: 'tortilla', qty: 0.1, unit: Unit.KILOGRAM },
      { name: 'Crema extra', price: 12, rmKey: 'crema', qty: 0.05, unit: Unit.LITER },
    ],
  },
  {
    key: 'picante',
    name: 'Nivel de picante',
    required: false,
    allowMultiple: false,
    min: 0,
    max: 1,
    mods: [
      { name: 'Suave', price: 0 },
      { name: 'Medio', price: 0 },
      { name: 'Bravo', price: 0 },
    ],
  },
]

// ─── Menu (categories + products) ────────────────────────────────────────────
type ProductDef = {
  name: string
  sku: string
  price: number
  desc?: string
  recipe?: Array<{ rm: string; qty: number }> // → InventoryMethod.RECIPE
  stockQty?: number // → InventoryMethod.QUANTITY (botellas / charcutería kg)
  unit?: Unit // measurement unit (charcutería: KILOGRAM — price = per kg)
  isAlcoholic?: boolean
  groups?: string[] // modifier group keys
}
type CategoryDef = { name: string; slug: string; icon?: string; products: ProductDef[] }

const MENU: CategoryDef[] = [
  {
    name: 'Desayunos',
    slug: 'desayunos',
    icon: 'sunrise',
    products: [
      {
        name: 'Chilaquiles verdes con pollo',
        sku: 'LR-DES-001',
        price: 145,
        desc: 'Totopos bañados en salsa verde con pollo deshebrado, crema y queso.',
        recipe: [
          { rm: 'tortilla', qty: 0.15 },
          { rm: 'salsaverde', qty: 0.25 },
          { rm: 'pollo', qty: 0.12 },
          { rm: 'queso', qty: 0.05 },
          { rm: 'crema', qty: 0.04 },
          { rm: 'cebolla', qty: 0.02 },
        ],
        groups: ['picante', 'extras'],
      },
      {
        name: 'Chilaquiles rojos con huevo',
        sku: 'LR-DES-002',
        price: 135,
        desc: 'Con salsa roja de la casa y huevo al gusto.',
        recipe: [
          { rm: 'tortilla', qty: 0.15 },
          { rm: 'salsaroja', qty: 0.25 },
          { rm: 'huevo', qty: 0.1 },
          { rm: 'queso', qty: 0.05 },
          { rm: 'crema', qty: 0.04 },
        ],
        groups: ['picante', 'huevos', 'extras'],
      },
      {
        name: 'Huevos al gusto',
        sku: 'LR-DES-003',
        price: 95,
        desc: 'Dos huevos con frijoles de la olla y tortillas.',
        recipe: [
          { rm: 'huevo', qty: 0.12 },
          { rm: 'jitomate', qty: 0.04 },
          { rm: 'cebolla', qty: 0.02 },
          { rm: 'frijol', qty: 0.08 },
        ],
        groups: ['huevos'],
      },
      {
        name: 'Molletes con pico de gallo',
        sku: 'LR-DES-004',
        price: 92,
        desc: 'Bolillo con frijoles refritos y queso gratinado.',
        recipe: [
          { rm: 'bolillo', qty: 2 },
          { rm: 'frijol', qty: 0.12 },
          { rm: 'queso', qty: 0.08 },
          { rm: 'jitomate', qty: 0.05 },
        ],
        groups: ['extras'],
      },
      {
        name: 'Hotcakes de la casa',
        sku: 'LR-DES-005',
        price: 88,
        desc: 'Tres hotcakes esponjosos con miel.',
        recipe: [{ rm: 'masa', qty: 0.18 }],
      },
      {
        name: 'Enfrijoladas de pollo',
        sku: 'LR-DES-006',
        price: 112,
        desc: 'Tortillas bañadas en frijol con pollo y crema.',
        recipe: [
          { rm: 'tortilla', qty: 0.12 },
          { rm: 'frijol', qty: 0.2 },
          { rm: 'pollo', qty: 0.1 },
          { rm: 'crema', qty: 0.05 },
          { rm: 'queso', qty: 0.04 },
        ],
      },
    ],
  },
  {
    name: 'Antojitos',
    slug: 'antojitos',
    icon: 'utensils',
    products: [
      {
        name: 'Guacamole con totopos',
        sku: 'LR-ANT-001',
        price: 98,
        desc: 'Aguacate machacado al momento.',
        recipe: [
          { rm: 'aguacate', qty: 0.25 },
          { rm: 'jitomate', qty: 0.05 },
          { rm: 'cebolla', qty: 0.03 },
          { rm: 'tortilla', qty: 0.08 },
        ],
      },
      {
        name: 'Queso fundido',
        sku: 'LR-ANT-002',
        price: 125,
        desc: 'Queso Oaxaca fundido con tortillas recién hechas.',
        recipe: [
          { rm: 'queso', qty: 0.18 },
          { rm: 'tortilla', qty: 0.09 },
        ],
        groups: ['tortilla', 'extras'],
      },
      {
        name: 'Sopa de tortilla',
        sku: 'LR-ANT-003',
        price: 88,
        desc: 'Caldillo de jitomate, julianas crujientes, aguacate y crema.',
        recipe: [
          { rm: 'tortilla', qty: 0.08 },
          { rm: 'jitomate', qty: 0.12 },
          { rm: 'crema', qty: 0.03 },
          { rm: 'aguacate', qty: 0.05 },
        ],
      },
      { name: 'Esquites de la casa', sku: 'LR-ANT-004', price: 58, desc: 'Con mayonesa, queso y chile piquín.' },
      {
        name: 'Tostadas de tinga (2 pzas)',
        sku: 'LR-ANT-005',
        price: 89,
        desc: 'Tinga de pollo sobre tostada con crema y queso.',
        recipe: [
          { rm: 'tortilla', qty: 0.06 },
          { rm: 'pollo', qty: 0.14 },
          { rm: 'crema', qty: 0.03 },
          { rm: 'cebolla', qty: 0.03 },
        ],
      },
      {
        name: 'Quesadillas (3 pzas)',
        sku: 'LR-ANT-006',
        price: 78,
        desc: 'De queso Oaxaca en tortilla recién hecha.',
        recipe: [
          { rm: 'tortilla', qty: 0.09 },
          { rm: 'queso', qty: 0.12 },
        ],
        groups: ['tortilla', 'extras'],
      },
    ],
  },
  {
    name: 'Tacos',
    slug: 'tacos',
    icon: 'flame',
    products: [
      {
        name: 'Orden de tacos al pastor (3)',
        sku: 'LR-TAC-001',
        price: 98,
        desc: 'Con piña, cebolla y cilantro.',
        recipe: [
          { rm: 'pastor', qty: 0.18 },
          { rm: 'tortilla', qty: 0.09 },
          { rm: 'cebolla', qty: 0.02 },
          { rm: 'pina', qty: 0.03 },
        ],
        groups: ['tortilla', 'picante'],
      },
      {
        name: 'Orden de tacos de arrachera (3)',
        sku: 'LR-TAC-002',
        price: 138,
        desc: 'Arrachera marinada con guacamole.',
        recipe: [
          { rm: 'arrachera', qty: 0.17 },
          { rm: 'tortilla', qty: 0.09 },
          { rm: 'cebolla', qty: 0.02 },
          { rm: 'aguacate', qty: 0.04 },
        ],
        groups: ['tortilla', 'extras'],
      },
      {
        name: 'Orden de tacos de suadero (3)',
        sku: 'LR-TAC-003',
        price: 92,
        desc: 'Suadero confitado estilo CDMX.',
        recipe: [
          { rm: 'suadero', qty: 0.17 },
          { rm: 'tortilla', qty: 0.09 },
          { rm: 'cebolla', qty: 0.02 },
        ],
        groups: ['tortilla', 'picante'],
      },
    ],
  },
  {
    name: 'Platos fuertes',
    slug: 'platos-fuertes',
    icon: 'chef-hat',
    products: [
      {
        name: 'Arrachera a la parrilla (300 g)',
        sku: 'LR-PLA-001',
        price: 268,
        desc: 'Con cebollitas, frijoles charros y guacamole.',
        recipe: [
          { rm: 'arrachera', qty: 0.32 },
          { rm: 'cebolla', qty: 0.03 },
          { rm: 'frijol', qty: 0.06 },
          { rm: 'aguacate', qty: 0.05 },
        ],
        groups: ['termino', 'extras'],
      },
      {
        name: 'Enchiladas suizas',
        sku: 'LR-PLA-002',
        price: 138,
        desc: 'Gratinadas, rellenas de pollo, salsa verde cremosa.',
        recipe: [
          { rm: 'tortilla', qty: 0.12 },
          { rm: 'pollo', qty: 0.13 },
          { rm: 'salsaverde', qty: 0.2 },
          { rm: 'queso', qty: 0.08 },
          { rm: 'crema', qty: 0.05 },
        ],
        groups: ['picante'],
      },
      {
        name: 'Milanesa de res con papas',
        sku: 'LR-PLA-003',
        price: 168,
        desc: 'Empanizada al momento con guarnición.',
        recipe: [
          { rm: 'bistec', qty: 0.22 },
          { rm: 'huevo', qty: 0.05 },
        ],
        groups: ['termino'],
      },
      {
        name: 'Pozole rojo',
        sku: 'LR-PLA-004',
        price: 118,
        desc: 'Con pollo, orégano, rábano y tostadas.',
        recipe: [
          { rm: 'pollo', qty: 0.15 },
          { rm: 'salsaroja', qty: 0.1 },
          { rm: 'tortilla', qty: 0.05 },
        ],
        groups: ['picante'],
      },
      {
        name: 'Mole de la casa con pollo',
        sku: 'LR-PLA-005',
        price: 148,
        desc: 'Receta familiar, con arroz y tortillas.',
        recipe: [
          { rm: 'pollo', qty: 0.25 },
          { rm: 'tortilla', qty: 0.06 },
        ],
      },
      {
        name: 'Pechuga a la plancha',
        sku: 'LR-PLA-006',
        price: 158,
        desc: 'Con ensalada y vegetales salteados.',
        recipe: [{ rm: 'pollo', qty: 0.28 }],
      },
    ],
  },
  {
    name: 'Bebidas',
    slug: 'bebidas',
    icon: 'coffee',
    products: [
      { name: 'Agua de horchata', sku: 'LR-BEB-001', price: 45, desc: 'Vaso 500 ml.' },
      { name: 'Agua de jamaica', sku: 'LR-BEB-002', price: 45, desc: 'Vaso 500 ml.' },
      { name: 'Limonada mineral', sku: 'LR-BEB-003', price: 48 },
      { name: 'Café de olla', sku: 'LR-BEB-004', price: 42, desc: 'Con piloncillo y canela.', recipe: [{ rm: 'cafe', qty: 0.02 }] },
      { name: 'Refresco', sku: 'LR-BEB-005', price: 40, stockQty: 120, unit: Unit.BOTTLE },
      { name: 'Agua embotellada', sku: 'LR-BEB-006', price: 30, stockQty: 80, unit: Unit.BOTTLE },
      { name: 'Cerveza clara', sku: 'LR-BEB-007', price: 58, stockQty: 96, unit: Unit.BOTTLE, isAlcoholic: true },
      { name: 'Michelada', sku: 'LR-BEB-008', price: 78, isAlcoholic: true },
    ],
  },
  {
    name: 'Postres',
    slug: 'postres',
    icon: 'cake',
    products: [
      { name: 'Flan napolitano', sku: 'LR-POS-001', price: 68 },
      { name: 'Pastel tres leches', sku: 'LR-POS-002', price: 78 },
      { name: 'Churros con cajeta', sku: 'LR-POS-003', price: 65 },
    ],
  },
  {
    // La cremería del grupo: productos por kg (stock en kg). Cuando el MVP de
    // báscula aterrice (spec 2026-07-18-venta-por-peso-bascula.md), estos
    // productos reciben soldByWeight=true y el POS captura el peso.
    name: 'Charcutería & Granel',
    slug: 'charcuteria-granel',
    icon: 'scale',
    products: [
      { name: 'Jamón serrano (kg)', sku: 'LR-CHA-001', price: 420, desc: 'Precio por kg.', stockQty: 8, unit: Unit.KILOGRAM },
      { name: 'Queso manchego (kg)', sku: 'LR-CHA-002', price: 380, desc: 'Precio por kg.', stockQty: 7.5, unit: Unit.KILOGRAM },
      { name: 'Salmón ahumado (kg)', sku: 'LR-CHA-003', price: 650, desc: 'Precio por kg.', stockQty: 4, unit: Unit.KILOGRAM },
      { name: 'Nuez de la India (kg)', sku: 'LR-CHA-004', price: 280, desc: 'Granel — precio por kg.', stockQty: 12, unit: Unit.KILOGRAM },
      { name: 'Granola artesanal (kg)', sku: 'LR-CHA-005', price: 150, desc: 'Granel — precio por kg.', stockQty: 15, unit: Unit.KILOGRAM },
    ],
  },
]

// ─── Areas / tables ──────────────────────────────────────────────────────────
const AREAS: Array<{
  name: string
  description: string
  tables: Array<{ number: string; capacity: number }>
  x0: number
  y0: number
  cols: number
}> = [
  {
    name: 'Salón Principal',
    description: 'Comedor interior',
    x0: 0.06,
    y0: 0.12,
    cols: 4,
    tables: Array.from({ length: 12 }, (_, i) => ({ number: `M${i + 1}`, capacity: i < 6 ? 4 : i < 10 ? 2 : 6 })),
  },
  {
    name: 'Terraza',
    description: 'Mesas al aire libre',
    x0: 0.62,
    y0: 0.12,
    cols: 2,
    tables: Array.from({ length: 6 }, (_, i) => ({ number: `T${i + 1}`, capacity: 4 })),
  },
  {
    name: 'Barra',
    description: 'Asientos de barra',
    x0: 0.06,
    y0: 0.78,
    cols: 4,
    tables: Array.from({ length: 4 }, (_, i) => ({ number: `B${i + 1}`, capacity: 2 })),
  },
]

// ─── Customers ───────────────────────────────────────────────────────────────
const CUSTOMERS = [
  { first: 'María', last: 'González', phone: '5554440001', points: 340 },
  { first: 'Carlos', last: 'Hernández', phone: '5554440002', points: 180 },
  { first: 'Ana Sofía', last: 'López', phone: '5554440003', points: 95 },
  { first: 'Roberto', last: 'Martínez', phone: '5554440004', points: 520 },
  { first: 'Laura', last: 'Sánchez', phone: '5554440005', points: 60 },
  { first: 'José Luis', last: 'Ramírez', phone: '5554440006', points: 275 },
  { first: 'Gabriela', last: 'Torres', phone: '5554440007', points: 130 },
  { first: 'Miguel Ángel', last: 'Flores', phone: '5554440008', points: 410 },
  { first: 'Daniela', last: 'Vega', phone: '5554440009', points: 85 },
  { first: 'Alejandro', last: 'Ruiz', phone: '5554440010', points: 200 },
]

const REVIEW_COMMENTS: Array<{ rating: number; text: string }> = [
  { rating: 5, text: 'Los chilaquiles verdes son los mejores del rumbo. Servicio rapidísimo.' },
  { rating: 5, text: 'La arrachera en su punto y el guacamole se hace al momento. Volvemos seguro.' },
  { rating: 4, text: 'Muy rica la comida corrida, la terraza es muy agradable.' },
  { rating: 5, text: 'Fernanda nos atendió increíble, todo salió rápido aunque estaba lleno.' },
  { rating: 4, text: 'Tacos al pastor muy buenos, el agua de horchata deliciosa.' },
  { rating: 5, text: 'El mole es de otro nivel. Ambiente familiar.' },
  { rating: 3, text: 'Rico todo pero tardó un poco la cuenta en hora pico.' },
  { rating: 5, text: 'Pedimos para llevar y estaba todo bien empacado y calientito.' },
  { rating: 4, text: 'Buenos precios y porciones generosas.' },
  { rating: 5, text: 'Las quesadillas con tortilla recién hecha, espectaculares.' },
  { rating: 4, text: 'El pozole muy sabroso, le faltó un poquito de picante a mi gusto.' },
  { rating: 5, text: 'Excelente atención de Luis, súper recomendado el queso fundido.' },
  { rating: 5, text: 'Desayunos muy completos y el café de olla auténtico.' },
  { rating: 4, text: 'Lugar limpio, servicio amable, el flan casero muy bueno.' },
]

// ─── Helpers ─────────────────────────────────────────────────────────────────
const d2 = (n: number) => +n.toFixed(2)
const d3 = (n: number) => +n.toFixed(3)
const rand = (n: number) => randomBytes(n).toString('hex').slice(0, n)
const pick = <T>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)]
/** Venue-local wall time → real UTC Date (host-tz independent — critical rule). */
const localAt = (ymd: string, hm: string) => fromZonedTime(`${ymd}T${hm}:00`, TZ)

async function resolveOrg(): Promise<string> {
  const template = await prisma.venue.findUnique({ where: { slug: 'avoqado-full' }, select: { organizationId: true } })
  if (template) return template.organizationId
  const org = await prisma.organization.upsert({
    where: { slug: 'avoqado-demos' },
    update: {},
    create: { name: 'Avoqado Demos', slug: 'avoqado-demos', email: 'demos@avoqado.io', phone: '5500000000', type: 'OTHER' },
  })
  logger.warn('   ⚠️ avoqado-full not found — venue will live under org "Avoqado Demos"')
  return org.id
}

async function cloneSingletonConfig(model: 'venueSettings' | 'reservationSettings' | 'loyaltyConfig', venueId: string): Promise<void> {
  const template = await prisma.venue.findUnique({ where: { slug: 'avoqado-full' }, select: { id: true } })
  if (!template) return
  const anyPrisma = prisma as any
  const src = await anyPrisma[model].findUnique({ where: { venueId: template.id } })
  if (!src) {
    logger.warn(`   ⚠️ template has no ${model} — skipping`)
    return
  }
  const { id: _id, venueId: _v, createdAt: _c, updatedAt: _u, ...rest } = src
  await anyPrisma[model].create({ data: { ...rest, venueId } })
  logger.info(`   ✅ cloned ${model} from avoqado-full`)
}

// ─── Teardown (FK-safe explicit order; PurchaseOrder.venue is onDelete:Restrict) ─
async function teardown() {
  const venue = await prisma.venue.findUnique({ where: { slug: NEW_SLUG }, select: { id: true, name: true, slug: true } })
  if (!venue) {
    logger.info(`Nothing to tear down — no venue with slug "${NEW_SLUG}".`)
    return
  }
  if (venue.slug !== NEW_SLUG) throw new Error('SAFETY ABORT: resolved venue is not the demo venue.')
  const venueId = venue.id
  logger.warn(`🗑️  Deleting venue "${venue.name}" (${venueId}) and all children…`)

  await prisma.journalEntry.deleteMany({ where: { venueId } })
  await prisma.review.deleteMany({ where: { venueId } })
  await prisma.payment.deleteMany({ where: { venueId } })
  const orderIds = (await prisma.order.findMany({ where: { venueId }, select: { id: true } })).map(o => o.id)
  if (orderIds.length) {
    await prisma.orderCustomer.deleteMany({ where: { orderId: { in: orderIds } } })
    const itemIds = (await prisma.orderItem.findMany({ where: { orderId: { in: orderIds } }, select: { id: true } })).map(i => i.id)
    if (itemIds.length) await prisma.orderItemModifier.deleteMany({ where: { orderItemId: { in: itemIds } } })
    await prisma.orderItem.deleteMany({ where: { orderId: { in: orderIds } } })
  }
  // Break Table.currentOrder ↔ Order cycle before deleting orders.
  await prisma.table.updateMany({ where: { venueId }, data: { currentOrderId: null } })
  await prisma.order.deleteMany({ where: { venueId } })
  await prisma.shift.deleteMany({ where: { venueId } })
  await prisma.reservation.deleteMany({ where: { venueId } })
  // Inventory chain. Recipes/RecipeLines (RecipeLine → RawMaterial is onDelete:
  // Restrict) must go BEFORE rawMaterial — the venue cascade would clear them
  // too, but it runs last, so delete them explicitly here first.
  await prisma.recipe.deleteMany({ where: { product: { venueId } } }) // cascades RecipeLine
  await prisma.rawMaterialMovement.deleteMany({ where: { venueId } })
  await prisma.stockBatch.deleteMany({ where: { venueId } })
  await prisma.purchaseOrder.deleteMany({ where: { venueId } }) // items cascade
  await prisma.supplier.deleteMany({ where: { venueId } }) // pricing cascades
  await prisma.rawMaterial.deleteMany({ where: { venueId } }) // Modifier.rawMaterialId is optional → SetNull
  await prisma.inventory.deleteMany({ where: { venueId } })

  // Area → Venue is onDelete: Restrict (unlike Table, which cascades), so it
  // blocks venue.delete unless removed first. Table.areaId is optional (SetNull),
  // so deleting areas while tables still exist just nulls the link; the venue
  // cascade then clears the tables.
  await prisma.area.deleteMany({ where: { venueId } })

  // Everything else cascades from the venue (products/recipes/categories/tables/
  // modifiers/features/customers/settings…).
  await prisma.venue.delete({ where: { id: venueId } })
  logger.info('✅ Teardown complete. avoqado-full / avoqado-fitness untouched.')
}

// ─── Seed ────────────────────────────────────────────────────────────────────
async function seed(force: boolean) {
  const existing = await prisma.venue.findUnique({ where: { slug: NEW_SLUG }, select: { id: true } })
  if (existing) {
    if (!force) throw new Error(`Venue "${NEW_SLUG}" already exists (${existing.id}). Use --teardown first, or --force.`)
    logger.warn(`--force: tearing down existing ${NEW_SLUG} (${existing.id}) before reseeding…`)
    await teardown()
  }

  const organizationId = await resolveOrg()

  // 1. Venue — grandfathered demo + dirección (auto-reorder la exige).
  const venue = await prisma.venue.create({
    data: {
      organizationId,
      name: NEW_NAME,
      slug: NEW_SLUG,
      type: 'RESTAURANT',
      timezone: TZ,
      currency: 'MXN',
      language: 'es',
      country: 'MX',
      city: 'Ciudad de México',
      state: 'CDMX',
      address: 'Av. Manuel González 255, Santa María la Ribera',
      zipCode: '06400',
      phone: '5556220148',
      email: 'hola@laribera.demo.avoqado.io',
      status: 'ACTIVE',
      active: true,
      kycStatus: 'VERIFIED',
      entityType: 'PERSONA_MORAL',
      seatCapExempt: true,
      primaryColor: ACCENT,
      operationalSince: subDays(new Date(), 400),
      // enabled:false ON PURPOSE for prod safety: with enabled:true the nightly
      // auto-reorder cron (and the post-payment real-time trigger) would create
      // POs and EMAIL the (fictional) supplier addresses every night from prod.
      // Off = the demo still shows the toggle + the pre-seeded auto-generated PO;
      // you flip it ON live during the meeting (a better demo moment). Config is
      // ready so "Run Now" works on demand.
      autoReorderConfig: { enabled: false, dailyCapMxn: 20000, minUrgency: 'LOW' },
    },
  })
  const venueId = venue.id
  logger.info(`🍽️  Venue created: ${NEW_NAME} → ${venueId}`)

  // 2. Config clones + features
  await cloneSingletonConfig('venueSettings', venueId)
  await cloneSingletonConfig('reservationSettings', venueId)
  await cloneSingletonConfig('loyaltyConfig', venueId)

  const features = await prisma.feature.findMany({ where: { code: { in: FEATURE_CODES }, active: true }, select: { id: true, code: true } })
  await saveVenueFeatures(
    venueId,
    features.map(f => f.id),
  )
  const missing = FEATURE_CODES.filter(c => !features.some(f => f.code === c))
  logger.info(`   ✅ Features: ${features.map(f => f.code).join(', ')}${missing.length ? ` (no existen: ${missing.join(', ')})` : ''}`)

  // 3. Staff: demo logins + meseros con PIN
  const staffByRole = new Map<string, string>()
  for (const login of DEMO_LOGINS) {
    const staff = await prisma.staff.findUnique({ where: { email: login.email }, select: { id: true } })
    if (!staff) {
      logger.warn(`   ⚠️ demo login ${login.email} not found in this DB — skipped`)
      continue
    }
    await prisma.staffVenue.upsert({
      where: { staffId_venueId: { staffId: staff.id, venueId } },
      update: {
        active: true,
        role: login.role,
        ...(login.role === StaffRole.CASHIER ? { pin: '5678' } : {}),
        ...(login.role === StaffRole.MANAGER ? { pin: '1111' } : {}),
      },
      create: {
        staffId: staff.id,
        venueId,
        role: login.role,
        active: true,
        ...(login.role === StaffRole.CASHIER ? { pin: '5678' } : {}),
        ...(login.role === StaffRole.MANAGER ? { pin: '1111' } : {}),
      },
    })
    staffByRole.set(login.role, staff.id)
  }

  const waiterIds: string[] = []
  for (const w of WAITERS) {
    const email = `${w.first}.${w.last}`.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/\s+/g, '') + '.laribera@avoqado.io'
    const staff = await prisma.staff.upsert({
      where: { email },
      update: { active: true },
      create: { email, firstName: w.first, lastName: w.last, active: true, emailVerified: true },
    })
    await prisma.staffVenue.upsert({
      where: { staffId_venueId: { staffId: staff.id, venueId } },
      update: { active: true, role: w.role, pin: w.pin },
      create: { staffId: staff.id, venueId, role: w.role, active: true, pin: w.pin },
    })
    if (w.role === StaffRole.WAITER) waiterIds.push(staff.id)
  }
  const fallbackStaffId = staffByRole.get('OWNER') ?? staffByRole.get('MANAGER') ?? waiterIds[0]
  const cashierId = staffByRole.get('CASHIER') ?? staffByRole.get('MANAGER') ?? fallbackStaffId
  logger.info(`   ✅ Staff: ${DEMO_LOGINS.length} logins demo + ${WAITERS.length} staff de piso (meseros con PIN)`)

  // 4. Raw materials + opening batches/movements (PO batches vienen en el paso 7)
  const rmByKey = new Map<string, { id: string; def: RM }>()
  for (const rm of RAW_MATERIALS) {
    const row = await prisma.rawMaterial.create({
      data: {
        venueId,
        name: rm.name,
        sku: rm.sku,
        category: rm.category,
        currentStock: rm.stock,
        unit: rm.unit,
        unitType: rm.unitType,
        minimumStock: rm.min,
        reorderPoint: rm.reorder,
        maximumStock: rm.max,
        costPerUnit: rm.cost,
        avgCostPerUnit: rm.cost,
        perishable: rm.perishable ?? false,
        shelfLifeDays: rm.shelfLifeDays,
        notifyOnLowStock: true,
        isDemo: true,
      },
    })
    rmByKey.set(rm.key, { id: row.id, def: rm })
  }
  logger.info(`   ✅ ${RAW_MATERIALS.length} materias primas (tortilla y aguacate BAJO reorder point a propósito)`)

  // 5. Menú: menu + categorías + productos + inventario + recetas + modificadores
  const menu = await prisma.menu.create({ data: { venueId, name: 'Carta La Ribera', type: 'REGULAR', active: true } })

  const groupIdByKey = new Map<string, string>()
  const modsByGroup = new Map<string, Array<{ id: string; name: string; price: number }>>()
  for (const [order, g] of MODIFIER_GROUPS.entries()) {
    const group = await prisma.modifierGroup.create({
      data: {
        venueId,
        name: g.name,
        required: g.required,
        allowMultiple: g.allowMultiple,
        minSelections: g.min,
        maxSelections: g.max,
        displayOrder: order,
        active: true,
        isDemo: true,
      },
    })
    groupIdByKey.set(g.key, group.id)
    const created: Array<{ id: string; name: string; price: number }> = []
    for (const m of g.mods) {
      const rmRef = m.rmKey ? rmByKey.get(m.rmKey) : undefined
      const mod = await prisma.modifier.create({
        data: {
          groupId: group.id,
          name: m.name,
          price: m.price,
          active: true,
          isDemo: true,
          ...(rmRef && m.qty && m.unit
            ? { rawMaterialId: rmRef.id, quantityPerUnit: m.qty, unit: m.unit, inventoryMode: 'ADDITION', cost: d2(rmRef.def.cost * m.qty) }
            : {}),
        },
      })
      created.push({ id: mod.id, name: m.name, price: m.price })
    }
    modsByGroup.set(g.key, created)
  }
  logger.info(`   ✅ ${MODIFIER_GROUPS.length} grupos de modificadores (extras ligados a inventario)`)

  type SeededProduct = { id: string; name: string; price: number; groups: string[]; catSlug: string }
  const products: SeededProduct[] = []
  for (const [ci, cat] of MENU.entries()) {
    const category = await prisma.menuCategory.create({
      data: {
        venueId,
        name: cat.name,
        slug: `lr-${cat.slug}`,
        displayOrder: ci,
        icon: cat.icon,
        color: ACCENT,
        active: true,
        isDemo: true,
      },
    })
    await prisma.menuCategoryAssignment.create({ data: { menuId: menu.id, categoryId: category.id, displayOrder: ci } })

    for (const [pi, p] of cat.products.entries()) {
      const hasRecipe = !!p.recipe?.length
      const hasStock = p.stockQty !== undefined
      const product = await prisma.product.create({
        data: {
          venueId,
          categoryId: category.id,
          sku: p.sku,
          name: p.name,
          description: p.desc,
          type: ProductType.FOOD_AND_BEV,
          price: p.price,
          displayOrder: pi,
          active: true,
          isAlcoholic: p.isAlcoholic ?? false,
          isDemo: true,
          trackInventory: hasRecipe || hasStock,
          inventoryMethod: hasRecipe ? InventoryMethod.RECIPE : hasStock ? InventoryMethod.QUANTITY : null,
          unit: p.unit ?? (hasStock ? Unit.UNIT : undefined),
        },
      })
      products.push({ id: product.id, name: p.name, price: p.price, groups: p.groups ?? [], catSlug: cat.slug })

      if (hasStock) {
        await prisma.inventory.create({
          data: {
            venueId,
            productId: product.id,
            currentStock: p.stockQty!,
            minimumStock: d2(Math.max(1, p.stockQty! * 0.2)),
            maximumStock: d2(p.stockQty! * 1.6),
            reservedStock: 0,
            isDemo: true,
          },
        })
      }

      if (hasRecipe) {
        let totalCost = 0
        for (const line of p.recipe!) totalCost += rmByKey.get(line.rm)!.def.cost * line.qty
        const recipe = await prisma.recipe.create({
          data: { productId: product.id, portionYield: 1, totalCost: +totalCost.toFixed(4), isDemo: true },
        })
        for (const [li, line] of p.recipe!.entries()) {
          const rmRef = rmByKey.get(line.rm)!
          await prisma.recipeLine.create({
            data: {
              recipeId: recipe.id,
              rawMaterialId: rmRef.id,
              quantity: line.qty,
              unit: rmRef.def.unit,
              costPerServing: +(rmRef.def.cost * line.qty).toFixed(4),
              displayOrder: li,
              isDemo: true,
            },
          })
        }
      }

      for (const [gi, gKey] of (p.groups ?? []).entries()) {
        const groupId = groupIdByKey.get(gKey)
        if (groupId) await prisma.productModifierGroup.create({ data: { productId: product.id, groupId, displayOrder: gi } })
      }
    }
    logger.info(`   ✅ Categoría "${cat.name}" + ${cat.products.length} productos`)
  }
  const recipeCount = MENU.flatMap(c => c.products).filter(p => p.recipe?.length).length
  logger.info(`   ✅ ${products.length} productos (${recipeCount} con receta que descuenta inventario)`)

  // 6. Áreas + mesas con plano
  const tableIds: string[] = []
  for (const areaDef of AREAS) {
    const area = await prisma.area.create({ data: { venueId, name: areaDef.name, description: areaDef.description, isDemo: true } })
    for (const [ti, t] of areaDef.tables.entries()) {
      const col = ti % areaDef.cols
      const row = Math.floor(ti / areaDef.cols)
      const table = await prisma.table.create({
        data: {
          venueId,
          areaId: area.id,
          number: t.number,
          capacity: t.capacity,
          qrCode: `LRD-${venueId.substring(0, 8)}-${t.number}`,
          active: true,
          positionX: +(areaDef.x0 + col * 0.09).toFixed(3),
          positionY: +(areaDef.y0 + row * 0.16).toFixed(3),
          shape: t.capacity <= 2 ? 'ROUND' : 'SQUARE',
          isDemo: true,
        },
      })
      tableIds.push(table.id)
    }
  }
  logger.info(`   ✅ ${AREAS.length} áreas / ${tableIds.length} mesas con posiciones de plano`)

  // 7. CEDIS: proveedores + pricing + POs (recibidas → batches FIFO reales)
  const cedis = await prisma.supplier.create({
    data: {
      venueId,
      name: 'CEDIS Central del Grupo',
      contactName: 'Almacén Central',
      email: 'cedis@grupolaribera.mx',
      phone: '5556220100',
      address: 'Calz. Vallejo 980, Industrial Vallejo',
      city: 'Ciudad de México',
      state: 'CDMX',
      country: 'MX',
      leadTimeDays: 1,
      rating: 5.0,
      reliabilityScore: 0.98,
      notes: 'Proveedor INTERNO — surte desde el centro de distribución del grupo. Pedidos antes de las 6 pm llegan al día siguiente.',
      active: true,
    },
  })
  const carnes = await prisma.supplier.create({
    data: {
      venueId,
      name: 'Carnes Selectas del Norte',
      contactName: 'Jorge Salinas',
      email: 'pedidos@carnesselectas.mx',
      phone: '5557881234',
      city: 'Ciudad de México',
      leadTimeDays: 2,
      rating: 4.4,
      reliabilityScore: 0.9,
      active: true,
    },
  })
  await prisma.supplier.create({
    data: {
      venueId,
      name: 'Distribuidora La Central',
      contactName: 'Mostrador mayoreo',
      email: 'ventas@lacentral.mx',
      phone: '5559034455',
      city: 'Ciudad de México',
      leadTimeDays: 3,
      rating: 3.8,
      reliabilityScore: 0.82,
      notes: 'Proveedor externo de respaldo (abarrotes).',
      active: true,
    },
  })

  const effectiveFrom = subDays(new Date(), 60)
  for (const [, { id: rmId, def }] of rmByKey) {
    const supplierId = def.meat ? carnes.id : cedis.id
    await prisma.supplierPricing.create({
      data: { supplierId, rawMaterialId: rmId, pricePerUnit: def.cost, unit: def.unit, minimumQuantity: 1, effectiveFrom, active: true },
    })
  }
  logger.info('   ✅ Proveedores: CEDIS Central (interno) + Carnes Selectas + La Central, con SupplierPricing por insumo')

  const poShort = venueId.substring(0, 6).toUpperCase()
  let poSeq = 0
  async function createPO(opts: {
    supplierId: string
    status: PurchaseOrderStatus
    daysAgo: number
    autoGenerated?: boolean
    receive?: boolean
    items: Array<{ rmKey: string; qty: number }>
    notes?: string
  }) {
    poSeq++
    const orderDate = subDays(new Date(), opts.daysAgo)
    let subtotal = 0
    const itemsData = opts.items.map(i => {
      const { def } = rmByKey.get(i.rmKey)!
      const total = d2(def.cost * i.qty)
      subtotal += total
      return { rmKey: i.rmKey, qty: i.qty, unitPrice: def.cost, total, unit: def.unit }
    })
    subtotal = d2(subtotal)
    const taxAmount = d2(subtotal * 0.16)
    const po = await prisma.purchaseOrder.create({
      data: {
        venueId,
        supplierId: opts.supplierId,
        orderNumber: `PO-${poShort}-${String(poSeq).padStart(4, '0')}`,
        status: opts.status,
        orderDate,
        expectedDeliveryDate: addDays(orderDate, 1),
        receivedDate: opts.receive ? addDays(orderDate, 1) : null,
        subtotal,
        taxAmount,
        taxRate: 0.16,
        total: d2(subtotal + taxAmount),
        autoGenerated: opts.autoGenerated ?? false,
        createdBy: fallbackStaffId,
        receivedBy: opts.receive ? cashierId : null,
        notes: opts.notes,
      },
    })
    for (const item of itemsData) {
      const rmRef = rmByKey.get(item.rmKey)!
      const poItem = await prisma.purchaseOrderItem.create({
        data: {
          purchaseOrderId: po.id,
          rawMaterialId: rmRef.id,
          quantityOrdered: item.qty,
          quantityReceived: opts.receive ? item.qty : 0,
          unit: item.unit,
          receiveStatus: opts.receive ? PurchaseOrderItemStatus.RECEIVED : PurchaseOrderItemStatus.PENDING,
          unitPrice: item.unitPrice,
          total: item.total,
        },
      })
      if (opts.receive) {
        // El batch del PO es ~80% del stock actual; el resto vive en un batch de apertura.
        const remaining = d3(rmRef.def.stock * 0.8)
        const receivedDate = addDays(orderDate, 1)
        const batch = await prisma.stockBatch.create({
          data: {
            venueId,
            rawMaterialId: rmRef.id,
            purchaseOrderItemId: poItem.id,
            batchNumber: `CEDIS-${format(receivedDate, 'yyyyMMdd')}-${rmRef.def.sku}`,
            initialQuantity: item.qty,
            remainingQuantity: remaining,
            unit: item.unit,
            costPerUnit: item.unitPrice,
            receivedDate,
            expirationDate: rmRef.def.perishable ? addDays(receivedDate, rmRef.def.shelfLifeDays ?? 7) : null,
            status: BatchStatus.ACTIVE,
          },
        })
        await prisma.rawMaterialMovement.create({
          data: {
            venueId,
            rawMaterialId: rmRef.id,
            batchId: batch.id,
            type: 'PURCHASE',
            quantity: item.qty,
            unit: item.unit,
            previousStock: d3(Math.max(0, rmRef.def.stock - item.qty)),
            newStock: rmRef.def.stock,
            costImpact: item.total,
            reason: `Recepción ${po.orderNumber}`,
            reference: po.orderNumber,
            createdAt: receivedDate,
          },
        })
      }
    }
    return po
  }

  // Batch de apertura (20% del stock) para que el FIFO tenga historia previa.
  const openingDate = subDays(new Date(), 28)
  for (const [, { id: rmId, def }] of rmByKey) {
    const remaining = d3(def.stock * 0.2)
    await prisma.stockBatch.create({
      data: {
        venueId,
        rawMaterialId: rmId,
        batchNumber: `APERTURA-${def.sku}`,
        initialQuantity: d3(remaining * 3),
        remainingQuantity: remaining,
        unit: def.unit,
        costPerUnit: def.cost,
        receivedDate: openingDate,
        expirationDate: def.perishable ? addDays(new Date(), Math.max(2, (def.shelfLifeDays ?? 7) - 1)) : null,
        status: BatchStatus.ACTIVE,
      },
    })
    await prisma.rawMaterialMovement.create({
      data: {
        venueId,
        rawMaterialId: rmId,
        type: 'ADJUSTMENT',
        quantity: d3(remaining * 3),
        unit: def.unit,
        previousStock: 0,
        newStock: d3(remaining * 3),
        costImpact: d2(def.cost * remaining * 3),
        reason: 'Inventario inicial',
        reference: 'APERTURA',
        createdAt: openingDate,
      },
    })
  }

  const nonMeat = RAW_MATERIALS.filter(r => !r.meat).map(r => r.key)
  const meats = RAW_MATERIALS.filter(r => r.meat).map(r => r.key)
  await createPO({
    supplierId: cedis.id,
    status: PurchaseOrderStatus.RECEIVED,
    daysAgo: 10,
    receive: true,
    items: nonMeat.map(k => ({ rmKey: k, qty: d3(rmByKey.get(k)!.def.stock * 1.0) })),
    notes: 'Resurtido semanal desde el CEDIS.',
  })
  await createPO({
    supplierId: carnes.id,
    status: PurchaseOrderStatus.RECEIVED,
    daysAgo: 4,
    receive: true,
    items: meats.map(k => ({ rmKey: k, qty: d3(rmByKey.get(k)!.def.stock * 1.0) })),
    notes: 'Pedido de cárnicos.',
  })
  await createPO({
    supplierId: cedis.id,
    status: PurchaseOrderStatus.SENT,
    daysAgo: 1,
    items: [
      { rmKey: 'tortilla', qty: 15 },
      { rmKey: 'aguacate', qty: 8 },
      { rmKey: 'salsaverde', qty: 6 },
    ],
    notes: 'En tránsito desde el CEDIS — llega mañana.',
  })
  await createPO({
    supplierId: cedis.id,
    status: PurchaseOrderStatus.PENDING_APPROVAL,
    daysAgo: 0,
    autoGenerated: true,
    items: [
      { rmKey: 'tortilla', qty: 12 },
      { rmKey: 'aguacate', qty: 7 },
    ],
    notes: 'Generada automáticamente: tortilla y aguacate cruzaron su punto de reorden.',
  })
  logger.info('   ✅ 4 órdenes de compra (2 RECIBIDAS con lotes FIFO, 1 SENT en tránsito, 1 PENDING_APPROVAL auto-generada)')

  // 8. Clientes
  const customers: Array<{ id: string; name: string; phone: string; email: string | null }> = []
  for (const c of CUSTOMERS) {
    const cust = await prisma.customer.create({
      data: {
        venueId,
        firstName: c.first,
        lastName: c.last,
        phone: c.phone,
        loyaltyPoints: c.points,
        totalVisits: Math.max(1, Math.round(c.points / 45)),
        firstVisitAt: subDays(new Date(), 90),
        lastVisitAt: subDays(new Date(), Math.floor(Math.random() * 6)),
        marketingConsent: true,
        active: true,
      },
    })
    customers.push({ id: cust.id, name: `${c.first} ${c.last}`, phone: c.phone, email: null })
  }
  logger.info(`   ✅ ${customers.length} clientes con puntos de lealtad`)

  // 9. Historia: shifts cerrados + órdenes + pagos + reviews (21 días, hora local MX)
  const foodProducts = products.filter(p => !['charcuteria-granel'].includes(p.catSlug))
  const breakfast = products.filter(p => p.catSlug === 'desayunos' || p.catSlug === 'bebidas')
  const drinkOrDessert = products.filter(p => p.catSlug === 'bebidas' || p.catSlug === 'postres')

  let orderSeq = 0
  let totalOrders = 0
  let reviewIdx = 0
  const reviewDays = new Set<number>()
  while (reviewDays.size < REVIEW_COMMENTS.length) reviewDays.add(1 + Math.floor(Math.random() * HISTORY_DAYS))

  for (let daysAgo = HISTORY_DAYS; daysAgo >= 1; daysAgo--) {
    const day = subDays(new Date(), daysAgo)
    const ymd = formatInTimeZone(day, TZ, 'yyyy-MM-dd')
    const dow = fromZonedTime(`${ymd}T12:00:00`, TZ).getUTCDay() // stable weekday
    const isWeekend = dow === 5 || dow === 6 // Fri/Sat rush
    const orderCount = isWeekend ? 24 + Math.floor(Math.random() * 11) : 14 + Math.floor(Math.random() * 8)

    const shiftStart = localAt(ymd, '08:30')
    const shiftEnd = localAt(ymd, '22:45')
    const shift = await prisma.shift.create({
      data: { venueId, staffId: cashierId, startTime: shiftStart, startingCash: 2000, status: ShiftStatus.CLOSED, endTime: shiftEnd },
    })

    let dayCash = 0
    let dayCard = 0
    let dayTips = 0
    let daySales = 0
    let dayProducts = 0

    for (let i = 0; i < orderCount; i++) {
      orderSeq++
      // Meal-hour distribution: 20% breakfast, 45% lunch, 35% dinner.
      const r = Math.random()
      const hour =
        r < 0.2 ? 9 + Math.floor(Math.random() * 3) : r < 0.65 ? 13 + Math.floor(Math.random() * 4) : 18 + Math.floor(Math.random() * 4)
      const minute = Math.floor(Math.random() * 60)
      const createdAt = localAt(ymd, `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}`)

      const pool = hour < 12 ? breakfast : Math.random() < 0.25 ? drinkOrDessert : foodProducts
      const numItems = 1 + Math.floor(Math.random() * 4)
      type Line = { product: SeededProduct; quantity: number; mods: Array<{ id: string; name: string; price: number }> }
      const lines: Line[] = []
      let subtotal = 0
      for (let j = 0; j < numItems; j++) {
        const product = pick(pool.length ? pool : foodProducts)
        const quantity = Math.random() < 0.75 ? 1 : 2
        const mods: Line['mods'] = []
        if (quantity === 1 && product.groups.length && Math.random() < 0.55) {
          const gKey = pick(product.groups)
          const groupMods = modsByGroup.get(gKey) ?? []
          if (groupMods.length) mods.push(pick(groupMods))
          if (gKey !== 'extras' && product.groups.includes('extras') && Math.random() < 0.3) {
            const extras = modsByGroup.get('extras') ?? []
            if (extras.length) mods.push(pick(extras))
          }
        }
        const lineBase = product.price * quantity + mods.reduce((s, m) => s + m.price, 0)
        subtotal += lineBase
        lines.push({ product, quantity, mods })
      }
      subtotal = d2(subtotal)
      const taxAmount = d2(subtotal * 0.16)
      const total = d2(subtotal + taxAmount)

      const isDineIn = Math.random() < 0.82
      const tableId = isDineIn ? pick(tableIds) : null
      const waiterId = pick(waiterIds)
      const customer = Math.random() < 0.5 ? pick(customers) : null
      const hasTip = Math.random() < 0.72
      const tipAmount = hasTip ? d2(total * (0.08 + Math.random() * 0.1)) : 0
      const srcR = Math.random()
      const source =
        srcR < 0.4 ? OrderSource.POS : srcR < 0.75 ? OrderSource.AVOQADO_ANDROID : srcR < 0.9 ? OrderSource.TPV : OrderSource.QR

      const order = await prisma.order.create({
        data: {
          venueId,
          shiftId: shift.id,
          tableId,
          customerId: customer?.id,
          customerName: customer?.name ?? null,
          customerPhone: customer?.phone ?? null,
          orderNumber: `LR-${String(orderSeq).padStart(4, '0')}`,
          type: isDineIn ? OrderType.DINE_IN : OrderType.TAKEOUT,
          source,
          status: OrderStatus.COMPLETED,
          paymentStatus: PaymentStatus.PAID,
          subtotal,
          taxAmount,
          total,
          tipAmount,
          createdById: waiterId,
          servedById: waiterId,
          createdAt,
          completedAt: addMinutes(createdAt, 35 + Math.floor(Math.random() * 40)),
        },
      })

      for (const line of lines) {
        const modsTotal = line.mods.reduce((s, m) => s + m.price, 0)
        const lineBase = line.product.price * line.quantity + modsTotal
        const item = await prisma.orderItem.create({
          // select id only: PROD (main) is one migration behind develop and lacks
          // OrderItem.course (20260717_add_order_item_course). Default RETURNING would
          // read that column → P2022. Selecting id keeps this script portable across
          // the drift (works on both local/develop and prod).
          select: { id: true },
          data: {
            orderId: order.id,
            productId: line.product.id,
            quantity: line.quantity,
            unitPrice: line.product.price,
            taxAmount: d2(lineBase * 0.16),
            total: d2(lineBase * 1.16),
          },
        })
        for (const m of line.mods) {
          await prisma.orderItemModifier.create({
            data: { orderItemId: item.id, modifierId: m.id, name: m.name, quantity: 1, price: m.price },
          })
        }
        dayProducts += line.quantity
      }

      if (customer) {
        await prisma.orderCustomer.create({ data: { orderId: order.id, customerId: customer.id, isPrimary: true, addedAt: createdAt } })
      }

      const mR = Math.random()
      const method = mR < 0.38 ? PaymentMethod.CASH : mR < 0.82 ? PaymentMethod.CREDIT_CARD : PaymentMethod.DEBIT_CARD
      const isCard = method !== PaymentMethod.CASH
      const payment = await prisma.payment.create({
        data: {
          venueId,
          orderId: order.id,
          shiftId: shift.id,
          amount: total,
          tipAmount,
          method,
          status: 'COMPLETED',
          feePercentage: isCard ? 0.025 : 0,
          feeAmount: isCard ? d2((total + tipAmount) * 0.025) : 0,
          netAmount: isCard ? d2((total + tipAmount) * 0.975) : d2(total + tipAmount),
          processedById: waiterId,
          createdAt: addMinutes(createdAt, 30 + Math.floor(Math.random() * 45)),
        },
      })

      daySales = d2(daySales + total)
      dayTips = d2(dayTips + tipAmount)
      if (isCard) dayCard = d2(dayCard + total + tipAmount)
      else dayCash = d2(dayCash + total + tipAmount)
      totalOrders++

      if (reviewDays.has(daysAgo) && reviewIdx < REVIEW_COMMENTS.length && i === 2) {
        const rv = REVIEW_COMMENTS[reviewIdx++]
        reviewDays.delete(daysAgo)
        await prisma.review.create({
          data: {
            venueId,
            paymentId: payment.id,
            servedById: waiterId,
            overallRating: rv.rating,
            foodRating: rv.rating,
            serviceRating: Math.min(5, rv.rating + (Math.random() < 0.3 ? 1 : 0)),
            ambienceRating: rv.rating,
            comment: rv.text,
            customerName: customer?.name ?? pick(CUSTOMERS.map(c => `${c.first} ${c.last}`)),
            source: ReviewSource.AVOQADO,
            createdAt: addMinutes(createdAt, 90),
          },
        })
      }
    }

    // Corte del día: declarado cuadra salvo 2 días con diferencia pequeña (realismo).
    const diff = daysAgo === 6 ? -37.5 : daysAgo === 13 ? 12 : 0
    await prisma.shift.update({
      where: { id: shift.id },
      data: {
        totalSales: daySales,
        totalTips: dayTips,
        totalOrders: orderCount,
        totalProductsSold: dayProducts,
        totalCashPayments: dayCash,
        totalCardPayments: dayCard,
        endingCash: d2(2000 + dayCash + diff),
        cashDeclared: d2(dayCash + diff),
        cardDeclared: dayCard,
        cashDifference: diff,
        notes: diff !== 0 ? 'Diferencia registrada en arqueo.' : null,
      },
    })
  }
  logger.info(`   ✅ Historia: ${HISTORY_DAYS} shifts CERRADOS · ${totalOrders} órdenes pagadas · ${REVIEW_COMMENTS.length} reseñas`)

  // 10. Reservaciones futuras (mesas)
  const tomorrow = formatInTimeZone(addDays(new Date(), 1), TZ, 'yyyy-MM-dd')
  const dayAfter = formatInTimeZone(addDays(new Date(), 2), TZ, 'yyyy-MM-dd')
  const reservations = [
    { ymd: tomorrow, hm: '14:00', name: 'Familia Sandoval', phone: '+525511223344', party: 6 },
    { ymd: dayAfter, hm: '20:00', name: 'Cumpleaños Regina', phone: '+525599887766', party: 8 },
  ]
  for (const r of reservations) {
    const startsAt = localAt(r.ymd, r.hm)
    await prisma.reservation.create({
      data: {
        venueId,
        confirmationCode: `LR-${rand(6).toUpperCase()}`,
        channel: ReservationChannel.DASHBOARD,
        status: ReservationStatus.CONFIRMED,
        startsAt,
        endsAt: addMinutes(startsAt, 90),
        duration: 90,
        partySize: r.party,
        guestName: r.name,
        guestPhone: r.phone,
        tableId: pick(tableIds),
        confirmedAt: new Date(),
      },
    })
  }
  logger.info(`   ✅ ${reservations.length} reservaciones futuras`)

  // 11. Resumen
  logger.info('')
  logger.info('════════════════════════ RESUMEN ════════════════════════')
  logger.info(`Venue:      ${NEW_NAME}  (${venueId})`)
  logger.info(`Slug:       ${NEW_SLUG} · type RESTAURANT · PREMIUM real (PLAN_PREMIUM) · grandfathered`)
  logger.info(`Dashboard:  /venues/${NEW_SLUG}/home`)
  logger.info(`Logins:     owner@owner.com / admin@admin.com / manager@manager.com / cashier@cashier.com (mismas claves demo de siempre)`)
  logger.info(`PINs piso:  Luis 1234 · Fernanda 2345 · Diego 3456 · Valeria 4567 · Cocina 8888 · Cashier 5678 · Manager 1111`)
  logger.info(
    `Menú:       ${MENU.length} categorías · ${products.length} productos · ${recipeCount} recetas · ${MODIFIER_GROUPS.length} grupos modificadores`,
  )
  logger.info(
    `Inventario: ${RAW_MATERIALS.length} insumos (⚠️ tortilla 9.2/10 y aguacate 5.4/6 bajo reorden) · charcutería en kg lista para báscula`,
  )
  logger.info(`CEDIS:      3 proveedores · 4 POs (2 recibidas c/lotes FIFO, 1 en tránsito, 1 auto-generada PENDING_APPROVAL)`)
  logger.info(`Historia:   ${HISTORY_DAYS} días · ${totalOrders} órdenes · ${HISTORY_DAYS} cortes cerrados · propinas/mixes de pago reales`)
  logger.info('══════════════════════════════════════════════════════════')
  logger.info('✅ Seed completo. avoqado-full / avoqado-fitness intactos.')
}

// ─── Main ────────────────────────────────────────────────────────────────────
async function main() {
  const args = process.argv.slice(2)
  const dbUrl = process.env.DATABASE_URL ?? ''
  const host = dbUrl.split('@')[1]?.split('/')[0] ?? 'unknown'
  const dbName = dbUrl.split('/').pop()?.split('?')[0] ?? 'unknown'
  logger.info(`🎯 Target DB: ${dbName} @ ${host}`)

  if (host.includes('render.com') && !args.includes('--prod')) {
    throw new Error('Target is PRODUCTION (render.com). Re-run with --prod to confirm.')
  }

  if (args.includes('--teardown')) {
    await teardown()
    return
  }
  await seed(args.includes('--force'))
}

main()
  .catch(err => {
    logger.error('❌ Failed:', err)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
