// AUTO-GENERATED base chart of accounts — DO NOT hand-edit the data; regenerate from the SAT research.
// Source: SAT código agrupador (c_CuentasSAT / Anexo 24), verified by multi-agent research + adversarial
// per-account checks (workflow catalogo-sat-research, 2026-06-16). Every código agrupador was confirmed
// against omawww.sat.gob.mx/.../codigo_agrupador.pdf. Group-headers (100/700) and one UNVERIFIED leaf
// (703.01) were dropped; two self-flagged sub-suffixes (115.03→115, 213.05→213) use the conservative mayor.
//
// This is the CATALOG (structure) only — no balances. Scope is (organizationId, rfc) = el contribuyente.

export interface SeedAccount {
  /** Número de cuenta en formato SAT (NumCta del Anexo 24). Clave de negocio dentro de (org, rfc). */
  code: string
  name: string
  /** Código agrupador del SAT (c_CuentasSAT). */
  satGroupingCode: string
  type: 'ACTIVO' | 'PASIVO' | 'CAPITAL' | 'INGRESO' | 'COSTO' | 'GASTO' | 'ORDEN'
  nature: 'DEUDORA' | 'ACREEDORA'
  /** Profundidad (1 = mayor, 2 = subcuenta). Derivado de la estructura del código. */
  level: number
  /** Código del padre (SubCtaDe), o null para cuentas de mayor. */
  parentCode: string | null
}

/** Catálogo base común a cualquier giro (83 cuentas). Se siembra para todo (org, rfc). */
export const BASE_CHART: SeedAccount[] = [
  { code: '101', name: 'Caja', satGroupingCode: '101', type: 'ACTIVO', nature: 'DEUDORA', level: 1, parentCode: null },
  { code: '101.01', name: 'Caja general', satGroupingCode: '101', type: 'ACTIVO', nature: 'DEUDORA', level: 2, parentCode: '101' },
  {
    code: '101.02',
    name: 'Caja chica / Fondo fijo',
    satGroupingCode: '101',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '101',
  },
  { code: '102', name: 'Bancos', satGroupingCode: '102', type: 'ACTIVO', nature: 'DEUDORA', level: 1, parentCode: null },
  { code: '102.01', name: 'Bancos nacionales', satGroupingCode: '102', type: 'ACTIVO', nature: 'DEUDORA', level: 2, parentCode: '102' },
  { code: '102.02', name: 'Bancos extranjeros', satGroupingCode: '102', type: 'ACTIVO', nature: 'DEUDORA', level: 2, parentCode: '102' },
  { code: '105', name: 'Clientes', satGroupingCode: '105', type: 'ACTIVO', nature: 'DEUDORA', level: 1, parentCode: null },
  {
    code: '105.01',
    name: 'Clientes nacionales',
    satGroupingCode: '105.01',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '105',
  },
  {
    code: '105.02',
    name: 'Clientes extranjeros',
    satGroupingCode: '105.02',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '105',
  },
  {
    code: '106',
    name: 'Cuentas y documentos por cobrar a corto plazo',
    satGroupingCode: '106',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 1,
    parentCode: null,
  },
  { code: '107', name: 'Deudores diversos', satGroupingCode: '107', type: 'ACTIVO', nature: 'DEUDORA', level: 1, parentCode: null },
  {
    code: '107.05',
    name: 'Otros deudores diversos',
    satGroupingCode: '107.05',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '107',
  },
  { code: '115', name: 'Inventario', satGroupingCode: '115', type: 'ACTIVO', nature: 'DEUDORA', level: 1, parentCode: null },
  {
    code: '115.01',
    name: 'Inventario (mercancias)',
    satGroupingCode: '115.01',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '115',
  },
  {
    code: '115.02',
    name: 'Materia prima y materiales',
    satGroupingCode: '115.02',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '115',
  },
  {
    code: '115.04',
    name: 'Productos terminados',
    satGroupingCode: '115.04',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '115',
  },
  {
    code: '118',
    name: 'Impuestos acreditables pagados',
    satGroupingCode: '118',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 1,
    parentCode: null,
  },
  {
    code: '118.01',
    name: 'IVA acreditable pagado',
    satGroupingCode: '118.01',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '118',
  },
  {
    code: '118.02',
    name: 'IVA acreditable de importacion pagado',
    satGroupingCode: '118.02',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '118',
  },
  {
    code: '119',
    name: 'Impuestos acreditables por pagar',
    satGroupingCode: '119',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 1,
    parentCode: null,
  },
  {
    code: '119.01',
    name: 'IVA pendiente de pago',
    satGroupingCode: '119.01',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '119',
  },
  { code: '120', name: 'Anticipo a proveedores', satGroupingCode: '120', type: 'ACTIVO', nature: 'DEUDORA', level: 1, parentCode: null },
  {
    code: '120.01',
    name: 'Anticipo a proveedores nacional',
    satGroupingCode: '120.01',
    type: 'ACTIVO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '120',
  },
  { code: '201', name: 'Proveedores', satGroupingCode: '201', type: 'PASIVO', nature: 'ACREEDORA', level: 1, parentCode: null },
  {
    code: '201.01',
    name: 'Proveedores nacionales',
    satGroupingCode: '201.01',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '201',
  },
  {
    code: '201.02',
    name: 'Proveedores extranjeros',
    satGroupingCode: '201.02',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '201',
  },
  {
    code: '205',
    name: 'Acreedores diversos a corto plazo',
    satGroupingCode: '205',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 1,
    parentCode: null,
  },
  {
    code: '205.02',
    name: 'Acreedores diversos a corto plazo nacional',
    satGroupingCode: '205.02',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '205',
  },
  {
    code: '205.06',
    name: 'Otros acreedores diversos a corto plazo',
    satGroupingCode: '205.06',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '205',
  },
  { code: '206', name: 'Anticipo de cliente', satGroupingCode: '206', type: 'PASIVO', nature: 'ACREEDORA', level: 1, parentCode: null },
  {
    code: '206.01',
    name: 'Anticipo de cliente nacional',
    satGroupingCode: '206.01',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '206',
  },
  {
    code: '208',
    name: 'Impuestos trasladados cobrados',
    satGroupingCode: '208',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 1,
    parentCode: null,
  },
  {
    code: '208.01',
    name: 'IVA trasladado cobrado',
    satGroupingCode: '208.01',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '208',
  },
  {
    code: '209',
    name: 'Impuestos trasladados no cobrados',
    satGroupingCode: '209',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 1,
    parentCode: null,
  },
  {
    code: '209.01',
    name: 'IVA trasladado no cobrado',
    satGroupingCode: '209.01',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '209',
  },
  {
    code: '213',
    name: 'Impuestos y derechos por pagar',
    satGroupingCode: '213',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 1,
    parentCode: null,
  },
  { code: '213.01', name: 'IVA por pagar', satGroupingCode: '213.01', type: 'PASIVO', nature: 'ACREEDORA', level: 2, parentCode: '213' },
  { code: '213.03', name: 'ISR por pagar', satGroupingCode: '213.03', type: 'PASIVO', nature: 'ACREEDORA', level: 2, parentCode: '213' },
  {
    code: '213.04',
    name: 'Impuesto estatal sobre nomina por pagar',
    satGroupingCode: '213.04',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '213',
  },
  { code: '216', name: 'Impuestos retenidos', satGroupingCode: '216', type: 'PASIVO', nature: 'ACREEDORA', level: 1, parentCode: null },
  {
    code: '216.01',
    name: 'Impuestos retenidos de ISR por sueldos y salarios',
    satGroupingCode: '216.01',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '216',
  },
  {
    code: '216.04',
    name: 'Impuestos retenidos de ISR por servicios profesionales',
    satGroupingCode: '216.04',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '216',
  },
  {
    code: '216.10',
    name: 'Impuestos retenidos de IVA',
    satGroupingCode: '216.10',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '216',
  },
  {
    code: '216.07',
    name: 'Cuotas de seguridad social retenidas a los trabajadores',
    satGroupingCode: '216.07',
    type: 'PASIVO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '216',
  },
  { code: '301', name: 'Capital social', satGroupingCode: '301', type: 'CAPITAL', nature: 'ACREEDORA', level: 1, parentCode: null },
  { code: '301.01', name: 'Capital fijo', satGroupingCode: '301.01', type: 'CAPITAL', nature: 'ACREEDORA', level: 2, parentCode: '301' },
  {
    code: '301.02',
    name: 'Capital variable',
    satGroupingCode: '301.02',
    type: 'CAPITAL',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '301',
  },
  { code: '303', name: 'Reserva legal', satGroupingCode: '303', type: 'CAPITAL', nature: 'ACREEDORA', level: 1, parentCode: null },
  {
    code: '304',
    name: 'Resultado de ejercicios anteriores',
    satGroupingCode: '304',
    type: 'CAPITAL',
    nature: 'ACREEDORA',
    level: 1,
    parentCode: null,
  },
  {
    code: '304.01',
    name: 'Utilidad de ejercicios anteriores',
    satGroupingCode: '304.01',
    type: 'CAPITAL',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '304',
  },
  {
    code: '304.02',
    name: 'Perdida de ejercicios anteriores',
    satGroupingCode: '304.02',
    type: 'CAPITAL',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '304',
  },
  {
    code: '305',
    name: 'Resultado del ejercicio',
    satGroupingCode: '305',
    type: 'CAPITAL',
    nature: 'ACREEDORA',
    level: 1,
    parentCode: null,
  },
  {
    code: '305.01',
    name: 'Utilidad del ejercicio',
    satGroupingCode: '305.01',
    type: 'CAPITAL',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '305',
  },
  {
    code: '305.02',
    name: 'Perdida del ejercicio',
    satGroupingCode: '305.02',
    type: 'CAPITAL',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '305',
  },
  { code: '401', name: 'Ingresos', satGroupingCode: '401', type: 'INGRESO', nature: 'ACREEDORA', level: 1, parentCode: null },
  {
    code: '401.01',
    name: 'Ventas y/o servicios gravados a la tasa general',
    satGroupingCode: '401.01',
    type: 'INGRESO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '401',
  },
  {
    code: '401.04',
    name: 'Ventas y/o servicios gravados a la tasa del 0%',
    satGroupingCode: '401.04',
    type: 'INGRESO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '401',
  },
  {
    code: '401.07',
    name: 'Ventas y/o servicios exentos',
    satGroupingCode: '401.07',
    type: 'INGRESO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '401',
  },
  {
    code: '402',
    name: 'Devoluciones, descuentos o bonificaciones sobre ingresos',
    satGroupingCode: '402',
    type: 'INGRESO',
    nature: 'DEUDORA',
    level: 1,
    parentCode: null,
  },
  {
    code: '402.01',
    name: 'Devoluciones, descuentos o bonificaciones sobre ventas y/o servicios a la tasa general',
    satGroupingCode: '402.01',
    type: 'INGRESO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '402',
  },
  { code: '403', name: 'Otros ingresos', satGroupingCode: '403', type: 'INGRESO', nature: 'ACREEDORA', level: 1, parentCode: null },
  { code: '403.01', name: 'Otros ingresos', satGroupingCode: '403.01', type: 'INGRESO', nature: 'ACREEDORA', level: 2, parentCode: '403' },
  {
    code: '501',
    name: 'Costo de venta y/o servicio',
    satGroupingCode: '501',
    type: 'COSTO',
    nature: 'DEUDORA',
    level: 1,
    parentCode: null,
  },
  { code: '501.01', name: 'Costo de venta', satGroupingCode: '501.01', type: 'COSTO', nature: 'DEUDORA', level: 2, parentCode: '501' },
  {
    code: '501.02',
    name: 'Costo de servicios (mano de obra)',
    satGroupingCode: '501.02',
    type: 'COSTO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '501',
  },
  { code: '502', name: 'Compras', satGroupingCode: '502', type: 'COSTO', nature: 'DEUDORA', level: 1, parentCode: null },
  {
    code: '503',
    name: 'Devoluciones, descuentos o bonificaciones sobre compras',
    satGroupingCode: '503',
    type: 'COSTO',
    nature: 'ACREEDORA',
    level: 1,
    parentCode: null,
  },
  { code: '601', name: 'Gastos generales', satGroupingCode: '601', type: 'GASTO', nature: 'DEUDORA', level: 1, parentCode: null },
  { code: '601.01', name: 'Sueldos y salarios', satGroupingCode: '601.01', type: 'GASTO', nature: 'DEUDORA', level: 2, parentCode: '601' },
  {
    code: '601.45',
    name: 'Arrendamiento a personas fisicas residentes nacionales',
    satGroupingCode: '601.45',
    type: 'GASTO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '601',
  },
  {
    code: '601.48',
    name: 'Combustibles y lubricantes',
    satGroupingCode: '601.48',
    type: 'GASTO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '601',
  },
  {
    code: '601.84',
    name: 'Otros gastos generales',
    satGroupingCode: '601.84',
    type: 'GASTO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '601',
  },
  {
    code: '601.85',
    name: 'Impuesto sobre nomina (gasto)',
    satGroupingCode: '601.85',
    type: 'GASTO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '601',
  },
  // Depreciación de inversiones (LISR 34-35): 601.86 = gasto (DEBE); 171/171.09 = depreciación acumulada
  // (HABER, contra-activo). 171.09 es la hoja SIEMPRE posteable — no la usa ningún giro, así el asiento
  // de depreciación resuelve una cuenta hoja en todos los locales.
  { code: '601.86', name: 'Depreciacion del ejercicio', satGroupingCode: '601.86', type: 'GASTO', nature: 'DEUDORA', level: 2, parentCode: '601' },
  { code: '171', name: 'Depreciacion acumulada de activos fijos', satGroupingCode: '171', type: 'ACTIVO', nature: 'ACREEDORA', level: 1, parentCode: null },
  {
    code: '171.09',
    name: 'Depreciacion acumulada del ejercicio',
    satGroupingCode: '171',
    type: 'ACTIVO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '171',
  },
  { code: '602', name: 'Gastos de venta', satGroupingCode: '602', type: 'GASTO', nature: 'DEUDORA', level: 1, parentCode: null },
  {
    code: '602.01',
    name: 'Sueldos y salarios (ventas)',
    satGroupingCode: '602.01',
    type: 'GASTO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '602',
  },
  { code: '603', name: 'Gastos de administracion', satGroupingCode: '603', type: 'GASTO', nature: 'DEUDORA', level: 1, parentCode: null },
  {
    code: '603.01',
    name: 'Sueldos y salarios (administracion)',
    satGroupingCode: '603.01',
    type: 'GASTO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '603',
  },
  { code: '701', name: 'Gastos financieros', satGroupingCode: '701', type: 'GASTO', nature: 'DEUDORA', level: 1, parentCode: null },
  {
    code: '701.04',
    name: 'Intereses a cargo bancario nacional',
    satGroupingCode: '701.04',
    type: 'GASTO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '701',
  },
  {
    code: '701.10',
    name: 'Comisiones bancarias',
    satGroupingCode: '701.10',
    type: 'GASTO',
    nature: 'DEUDORA',
    level: 2,
    parentCode: '701',
  },
  { code: '702', name: 'Productos financieros', satGroupingCode: '702', type: 'INGRESO', nature: 'ACREEDORA', level: 1, parentCode: null },
  {
    code: '702.01',
    name: 'Utilidad cambiaria',
    satGroupingCode: '702.01',
    type: 'INGRESO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '702',
  },
  {
    code: '702.04',
    name: 'Intereses a favor bancarios nacional',
    satGroupingCode: '702.04',
    type: 'INGRESO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '702',
  },
  { code: '703', name: 'Otros gastos', satGroupingCode: '703', type: 'GASTO', nature: 'DEUDORA', level: 1, parentCode: null },
  { code: '704', name: 'Otros productos', satGroupingCode: '704', type: 'INGRESO', nature: 'ACREEDORA', level: 1, parentCode: null },
  {
    code: '704.01',
    name: 'Ganancia en venta y/o baja de activos',
    satGroupingCode: '704.01',
    type: 'INGRESO',
    nature: 'ACREEDORA',
    level: 2,
    parentCode: '704',
  },
]

/** Cuentas extra por giro (deduped vs BASE_CHART). Mapa por categoría interna. */
export const SECTOR_EXTRAS: Record<string, SeedAccount[]> = {
  restaurante: [
    {
      code: '153',
      name: 'Maquinaria y equipo (cocina)',
      satGroupingCode: '153',
      type: 'ACTIVO',
      nature: 'DEUDORA',
      level: 1,
      parentCode: null,
    },
    {
      code: '115.03',
      name: 'Inventario de bebidas y vinos',
      satGroupingCode: '115',
      type: 'ACTIVO',
      nature: 'DEUDORA',
      level: 2,
      parentCode: '115',
    },
    {
      code: '118.03',
      name: 'IEPS acreditable pagado',
      satGroupingCode: '118.03',
      type: 'ACTIVO',
      nature: 'DEUDORA',
      level: 2,
      parentCode: '118',
    },
    {
      code: '153.01',
      name: 'Maquinaria y equipo de cocina',
      satGroupingCode: '153.01',
      type: 'ACTIVO',
      nature: 'DEUDORA',
      level: 2,
      parentCode: '153',
    },
    {
      code: '208.02',
      name: 'IEPS trasladado cobrado',
      satGroupingCode: '208.02',
      type: 'PASIVO',
      nature: 'ACREEDORA',
      level: 2,
      parentCode: '208',
    },
    {
      code: '209.02',
      name: 'IEPS trasladado no cobrado',
      satGroupingCode: '209.02',
      type: 'PASIVO',
      nature: 'ACREEDORA',
      level: 2,
      parentCode: '209',
    },
    { code: '213.02', name: 'IEPS por pagar', satGroupingCode: '213.02', type: 'PASIVO', nature: 'ACREEDORA', level: 2, parentCode: '213' },
  ],
  retail: [
    {
      code: '153',
      name: 'Maquinaria y equipo (refrigeración/exhibición)',
      satGroupingCode: '153',
      type: 'ACTIVO',
      nature: 'DEUDORA',
      level: 1,
      parentCode: null,
    },
    {
      code: '156',
      name: 'Equipo de cómputo (punto de venta)',
      satGroupingCode: '156',
      type: 'ACTIVO',
      nature: 'DEUDORA',
      level: 1,
      parentCode: null,
    },
    {
      code: '171',
      name: 'Depreciación acumulada de activos fijos',
      satGroupingCode: '171',
      type: 'ACTIVO',
      nature: 'ACREEDORA',
      level: 1,
      parentCode: null,
    },
  ],
  servicios: [
    { code: '156', name: 'Equipo de cómputo', satGroupingCode: '156', type: 'ACTIVO', nature: 'DEUDORA', level: 1, parentCode: null },
    { code: '187', name: 'Pagos anticipados', satGroupingCode: '187', type: 'ACTIVO', nature: 'DEUDORA', level: 1, parentCode: null },
    {
      code: '187.01',
      name: 'Seguros y fianzas pagados por anticipado',
      satGroupingCode: '187.01',
      type: 'ACTIVO',
      nature: 'DEUDORA',
      level: 2,
      parentCode: '187',
    },
  ],
  gimnasio: [
    {
      code: '153',
      name: 'Maquinaria y equipo (equipo de ejercicio)',
      satGroupingCode: '153',
      type: 'ACTIVO',
      nature: 'DEUDORA',
      level: 1,
      parentCode: null,
    },
    {
      code: '171',
      name: 'Depreciación acumulada de activos fijos',
      satGroupingCode: '171',
      type: 'ACTIVO',
      nature: 'ACREEDORA',
      level: 1,
      parentCode: null,
    },
    {
      code: '153.01',
      name: 'Equipo de ejercicio y acondicionamiento',
      satGroupingCode: '153.01',
      type: 'ACTIVO',
      nature: 'DEUDORA',
      level: 2,
      parentCode: '153',
    },
    {
      code: '171.02',
      name: 'Depreciación acumulada de maquinaria y equipo',
      satGroupingCode: '171.02',
      type: 'ACTIVO',
      nature: 'ACREEDORA',
      level: 2,
      parentCode: '171',
    },
  ],
  hotel: [
    {
      code: '152',
      name: 'Edificios (inmueble del hotel)',
      satGroupingCode: '152',
      type: 'ACTIVO',
      nature: 'DEUDORA',
      level: 1,
      parentCode: null,
    },
    {
      code: '155',
      name: 'Mobiliario y equipo (habitaciones)',
      satGroupingCode: '155',
      type: 'ACTIVO',
      nature: 'DEUDORA',
      level: 1,
      parentCode: null,
    },
    {
      code: '171',
      name: 'Depreciación acumulada',
      satGroupingCode: '171',
      type: 'ACTIVO',
      nature: 'ACREEDORA',
      level: 1,
      parentCode: null,
    },
    { code: '184', name: 'Depósitos en garantía', satGroupingCode: '184', type: 'ACTIVO', nature: 'DEUDORA', level: 1, parentCode: null },
    {
      code: '118.03',
      name: 'IEPS acreditable pagado',
      satGroupingCode: '118.03',
      type: 'ACTIVO',
      nature: 'DEUDORA',
      level: 2,
      parentCode: '118',
    },
    {
      code: '171.01',
      name: 'Depreciación acumulada de edificios',
      satGroupingCode: '171.01',
      type: 'ACTIVO',
      nature: 'ACREEDORA',
      level: 2,
      parentCode: '171',
    },
    {
      code: '208.02',
      name: 'IEPS trasladado cobrado',
      satGroupingCode: '208.02',
      type: 'PASIVO',
      nature: 'ACREEDORA',
      level: 2,
      parentCode: '208',
    },
    { code: '213.02', name: 'IEPS por pagar', satGroupingCode: '213.02', type: 'PASIVO', nature: 'ACREEDORA', level: 2, parentCode: '213' },
    {
      code: '213.05',
      name: 'Impuesto sobre hospedaje por pagar (ISH)',
      satGroupingCode: '213',
      type: 'PASIVO',
      nature: 'ACREEDORA',
      level: 2,
      parentCode: '213',
    },
  ],
}
