import { BusinessType, VenueOperationalRole } from '@prisma/client'
import { createHash } from 'crypto'
import prisma from '@/utils/prismaClient'
import { resolveMasterCatalogAccess } from '@/services/master-catalog/masterCatalogAccess.service'
import { writeCatalogAudit } from '@/services/master-catalog/catalogAudit.service'
import { acquireCatalogMutationLock } from '@/services/master-catalog/catalogMutationLock.service'
import {
  CATALOG_VALIDATION_BASELINE_V1,
  confirmCatalogValidationProfile,
  previewCatalogValidationProfile,
} from '@/services/master-catalog/catalogValidation.service'
import type { CatalogCommandContext } from '@/types/master-catalog'

jest.mock('@/utils/prismaClient', () => ({
  __esModule: true,
  default: {
    $transaction: jest.fn(),
    catalogValidationProfile: { findMany: jest.fn(), updateMany: jest.fn(), create: jest.fn() },
    catalogIdempotencyRecord: { findFirst: jest.fn(), create: jest.fn(), update: jest.fn(), updateMany: jest.fn() },
    $executeRaw: jest.fn(),
  },
}))

jest.mock('@/services/master-catalog/masterCatalogAccess.service', () => ({
  resolveMasterCatalogAccess: jest.fn(),
}))

jest.mock('@/services/master-catalog/catalogAudit.service', () => ({
  writeCatalogAudit: jest.fn(),
}))

jest.mock('@/services/master-catalog/catalogMutationLock.service', () => ({
  acquireCatalogMutationLock: jest.fn(),
}))

const context: CatalogCommandContext = {
  organizationId: 'org-1',
  actor: { type: 'HUMAN', staffId: 'staff-owner', impersonating: false },
  orgRole: 'OWNER',
}

const now = new Date('2026-08-08T12:00:00.000Z')

// WHY: Profile dependencies are generated by preview, so this helper captures
// the persisted record and feeds that exact immutable snapshot into confirm.
function createdPreviewRecord() {
  return (prisma.catalogIdempotencyRecord.create as jest.Mock).mock.calls[0][0].data
}

describe('validation-profile preview and confirm', () => {
  beforeEach(() => {
    jest.clearAllMocks()
    jest.useFakeTimers().setSystemTime(now)
    ;(prisma.$transaction as jest.Mock).mockImplementation(async (callback: any) => callback(prisma))
    ;(prisma.$executeRaw as jest.Mock).mockResolvedValue(1)
    ;(prisma.catalogValidationProfile.findMany as jest.Mock).mockResolvedValue([])
    ;(prisma.catalogValidationProfile.updateMany as jest.Mock).mockResolvedValue({ count: 0 })
    ;(prisma.catalogValidationProfile.create as jest.Mock).mockImplementation(async ({ data }: any) => ({
      id: 'profile-1',
      profileVersion: data.profileVersion,
      rulesSchemaVersion: data.rulesSchemaVersion,
      active: data.active,
    }))
    ;(prisma.catalogIdempotencyRecord.create as jest.Mock).mockImplementation(async ({ data }: any) => ({
      id: 'profile-batch-1',
      ...data,
      createdAt: now,
      updatedAt: now,
    }))
    ;(prisma.catalogIdempotencyRecord.findFirst as jest.Mock).mockResolvedValue(null)
    ;(prisma.catalogIdempotencyRecord.updateMany as jest.Mock).mockResolvedValue({ count: 1 })
    ;(resolveMasterCatalogAccess as jest.Mock).mockResolvedValue({
      canMutateContent: true,
      canConfigureControlPlane: true,
      reasonCode: 'ACCESSIBLE',
    })
    ;(writeCatalogAudit as jest.Mock).mockResolvedValue({ id: 'audit-1' })
    ;(acquireCatalogMutationLock as jest.Mock).mockResolvedValue(undefined)
  })

  afterEach(() => jest.useRealTimers())

  it('persists only a SHA-256 token hash in the exclusive idempotency record', async () => {
    const preview = await previewCatalogValidationProfile(context, {
      idempotencyKey: 'profile-key-1',
      name: 'PITS food STORE',
      businessType: BusinessType.RESTAURANT,
      operationalRole: VenueOperationalRole.STORE,
      requiredFields: ['supplierCode'],
      additionalRules: { enforcePositiveShelfLife: true },
    })

    const create = (prisma.catalogIdempotencyRecord.create as jest.Mock).mock.calls[0][0].data
    expect(create.operation).toBe('VALIDATION_PROFILE_CHANGE')
    expect(create.state).toBe('PREVIEWED')
    expect(create.previewTokenHash).toBe(createHash('sha256').update(preview.previewToken).digest('hex'))
    expect(create.previewTokenHash).not.toContain(preview.previewToken)
    expect(create.targetHash).toMatch(/^[a-f0-9]{64}$/)
    expect(create.dependencies).toEqual(
      expect.objectContaining({ schemaVersion: 1, profileSetHash: expect.stringMatching(/^[a-f0-9]{64}$/) }),
    )
    expect(preview).toEqual(
      expect.objectContaining({
        profileBatchId: 'profile-batch-1',
        rulesSchemaVersion: 1,
        proposedProfileVersion: 1,
        requiredFields: expect.arrayContaining([...CATALOG_VALIDATION_BASELINE_V1, 'supplierCode']),
      }),
    )
  })

  it.each([
    ['non-string name', { name: 42 }],
    ['non-string required field', { requiredFields: [42] }],
    ['non-object additional rules', { additionalRules: ['not-an-object'] }],
    ['oversized additional rules', { additionalRules: { x: Array.from({ length: 4_095 }, () => true) } }],
  ])('maps %s to a validation error instead of leaking a TypeError', async (_label, overrides) => {
    await expect(
      previewCatalogValidationProfile(context, {
        idempotencyKey: 'runtime-boundary',
        name: 'runtime boundary',
        requiredFields: [],
        ...(overrides as any),
      }),
    ).rejects.toMatchObject({ statusCode: 422 })
  })

  it('keeps idempotency keys opaque and byte-exact', async () => {
    await previewCatalogValidationProfile(context, {
      idempotencyKey: '  opaque-key  ',
      name: 'opaque key profile',
      requiredFields: [],
    })

    expect(createdPreviewRecord().idempotencyKey).toBe('  opaque-key  ')
  })

  it('re-reads a concurrent P2002 reservation and never invents or re-exposes the raw preview token', async () => {
    ;(prisma.catalogIdempotencyRecord.create as jest.Mock).mockRejectedValueOnce({ code: 'P2002' })
    ;(prisma.catalogIdempotencyRecord.findFirst as jest.Mock).mockImplementation(async () => {
      const attempted = createdPreviewRecord()
      return {
        id: 'existing-profile-batch',
        organizationId: 'org-1',
        operation: 'VALIDATION_PROFILE_CHANGE',
        idempotencyKey: 'concurrent-preview-key',
        requestHash: attempted.requestHash,
        state: 'PREVIEWED',
      }
    })

    await expect(
      previewCatalogValidationProfile(context, {
        idempotencyKey: 'concurrent-preview-key',
        name: 'concurrent preview',
        requiredFields: ['supplierCode'],
      }),
    ).rejects.toMatchObject({ statusCode: 409, code: 'CATALOG_VALIDATION_PROFILE_PREVIEW_TOKEN_NOT_RECOVERABLE' })
    expect(prisma.catalogIdempotencyRecord.create).toHaveBeenCalledTimes(1)
    expect(prisma.catalogIdempotencyRecord.findFirst).toHaveBeenCalledWith({
      where: {
        organizationId: 'org-1',
        operation: 'VALIDATION_PROFILE_CHANGE',
        idempotencyKey: 'concurrent-preview-key',
      },
    })
  })

  it('maps a reused idempotency key with a different target hash to stable 409', async () => {
    ;(prisma.catalogIdempotencyRecord.create as jest.Mock).mockRejectedValueOnce({ code: 'P2002' })
    ;(prisma.catalogIdempotencyRecord.findFirst as jest.Mock).mockResolvedValue({
      id: 'existing-other-target',
      requestHash: '0'.repeat(64),
      state: 'PREVIEWED',
    })

    await expect(
      previewCatalogValidationProfile(context, {
        idempotencyKey: 'reused-key',
        name: 'new target',
        requiredFields: [],
      }),
    ).rejects.toMatchObject({ statusCode: 409, code: 'IDEMPOTENCY_KEY_REUSED' })
    expect(prisma.catalogIdempotencyRecord.create).toHaveBeenCalledTimes(1)
  })

  it('fails predictably before PostgreSQL Int profileVersion overflows', async () => {
    ;(prisma.catalogValidationProfile.findMany as jest.Mock).mockResolvedValue([
      {
        id: 'profile-max-int',
        profileVersion: 2_147_483_647,
        rulesSchemaVersion: 1,
        businessType: null,
        operationalRole: null,
        requiredFields: [],
        additionalRules: null,
        active: false,
        updatedAt: now,
      },
    ])

    await expect(
      previewCatalogValidationProfile(context, {
        idempotencyKey: 'profile-max-version',
        name: 'max version',
        requiredFields: [],
      }),
    ).rejects.toMatchObject({ statusCode: 409, code: 'CATALOG_VALIDATION_PROFILE_VERSION_EXHAUSTED' })
    expect(prisma.catalogIdempotencyRecord.create).not.toHaveBeenCalled()
  })

  it('rejects relaxation directives instead of weakening the H1 baseline', async () => {
    await expect(
      previewCatalogValidationProfile(context, {
        idempotencyKey: 'profile-key-relax',
        name: 'invalid relaxation',
        requiredFields: [],
        additionalRules: { removeRequiredFields: ['sku'] } as any,
      }),
    ).rejects.toMatchObject({ statusCode: 422 })
    expect(prisma.catalogIdempotencyRecord.create).not.toHaveBeenCalled()
  })

  it('revalidates OWNER/CORE, serializes organization+name, versions globally, and deactivates only the exact scope', async () => {
    const globalVersionFromAnotherScope = {
      id: 'profile-global-version-4',
      profileVersion: 4,
      rulesSchemaVersion: 1,
      businessType: BusinessType.RETAIL_STORE,
      operationalRole: null,
      requiredFields: ['otherScopeField'],
      additionalRules: null,
      active: false,
      updatedAt: new Date('2026-08-01T00:00:00.000Z'),
    }
    // WHY: The preview and confirm see the same global name-version set; the
    // different scope still raises the next globally unique version to five.
    ;(prisma.catalogValidationProfile.findMany as jest.Mock).mockResolvedValue([globalVersionFromAnotherScope])
    const preview = await previewCatalogValidationProfile(context, {
      idempotencyKey: 'profile-key-confirm',
      name: 'PITS food STORE',
      businessType: BusinessType.RESTAURANT,
      operationalRole: VenueOperationalRole.STORE,
      requiredFields: ['supplierCode'],
      additionalRules: { enforcePositiveShelfLife: true },
    })
    const persisted = createdPreviewRecord()
    ;(prisma.catalogIdempotencyRecord.findFirst as jest.Mock).mockResolvedValue({
      id: 'profile-batch-1',
      organizationId: 'org-1',
      operation: 'VALIDATION_PROFILE_CHANGE',
      idempotencyKey: 'profile-key-confirm',
      state: 'PREVIEWED',
      targetHash: persisted.targetHash,
      previewTokenHash: persisted.previewTokenHash,
      previewExpiresAt: persisted.previewExpiresAt,
      dependencies: persisted.dependencies,
      actorType: 'HUMAN',
      staffId: 'staff-owner',
    })

    const result = await confirmCatalogValidationProfile(context, {
      profileBatchId: 'profile-batch-1',
      idempotencyKey: 'profile-key-confirm',
      previewToken: preview.previewToken,
      confirm: true,
    })

    expect(resolveMasterCatalogAccess).toHaveBeenCalledWith(
      expect.objectContaining({ capability: 'MANAGE_PROFILE', requiredGate: 'CORE', prisma }),
    )
    expect(resolveMasterCatalogAccess).toHaveBeenCalledTimes(2)
    expect(acquireCatalogMutationLock).toHaveBeenCalledWith(prisma, context.organizationId)
    expect((acquireCatalogMutationLock as jest.Mock).mock.invocationCallOrder[0]).toBeLessThan(
      (prisma.$executeRaw as jest.Mock).mock.invocationCallOrder[0],
    )
    expect(prisma.$executeRaw).toHaveBeenCalledTimes(1)
    expect(prisma.catalogValidationProfile.updateMany).toHaveBeenCalledWith({
      where: {
        organizationId: 'org-1',
        name: 'PITS food STORE',
        businessType: BusinessType.RESTAURANT,
        operationalRole: VenueOperationalRole.STORE,
        active: true,
      },
      data: { active: false },
    })
    expect(prisma.catalogValidationProfile.create).toHaveBeenCalledWith(
      expect.objectContaining({ data: expect.objectContaining({ profileVersion: 5, rulesSchemaVersion: 1, active: true }) }),
    )
    expect(writeCatalogAudit).toHaveBeenCalledTimes(1)
    // WHY: Business audit content must be complete without opaque dependency hashes.
    expect((writeCatalogAudit as jest.Mock).mock.calls[0][1].after.additionalRules).toEqual({ enforcePositiveShelfLife: true })
    expect(prisma.catalogIdempotencyRecord.updateMany).toHaveBeenCalledWith(
      expect.objectContaining({
        where: expect.objectContaining({ id: 'profile-batch-1', state: 'PREVIEWED' }),
      }),
    )
    expect(result).toEqual(expect.objectContaining({ profileBatchId: 'profile-batch-1', profileVersion: 5 }))
  })

  it('re-reads the idempotency row after the advisory lock and recovers a concurrent APPLIED result', async () => {
    const preview = await previewCatalogValidationProfile(context, {
      idempotencyKey: 'profile-key-retry',
      name: 'concurrent retry',
      requiredFields: ['supplierCode'],
    })
    const persisted = createdPreviewRecord()
    const previewed = {
      id: 'profile-batch-1',
      organizationId: 'org-1',
      operation: 'VALIDATION_PROFILE_CHANGE',
      idempotencyKey: 'profile-key-retry',
      state: 'PREVIEWED',
      targetHash: persisted.targetHash,
      previewTokenHash: persisted.previewTokenHash,
      previewExpiresAt: persisted.previewExpiresAt,
      dependencies: persisted.dependencies,
      result: null,
      actorType: 'HUMAN',
      staffId: 'staff-owner',
    }
    const recovered = {
      profileBatchId: 'profile-batch-1',
      profileId: 'profile-winner',
      profileVersion: 1,
      rulesSchemaVersion: 1,
      active: true,
    }
    ;(prisma.catalogIdempotencyRecord.findFirst as jest.Mock).mockResolvedValueOnce(previewed).mockResolvedValueOnce({
      ...previewed,
      state: 'APPLIED',
      resourceType: 'CatalogValidationProfile',
      resourceId: 'profile-winner',
      result: recovered,
    })

    await expect(
      confirmCatalogValidationProfile(context, {
        profileBatchId: 'profile-batch-1',
        idempotencyKey: 'profile-key-retry',
        previewToken: preview.previewToken,
        confirm: true,
      }),
    ).resolves.toEqual(recovered)
    expect(prisma.catalogValidationProfile.create).not.toHaveBeenCalled()
  })

  it('detects profile content changes even when updatedAt and scope do not move', async () => {
    const sameTimestamp = new Date('2026-08-08T11:00:00.000Z')
    const row = {
      id: 'profile-content',
      profileVersion: 1,
      rulesSchemaVersion: 1,
      businessType: null,
      operationalRole: null,
      requiredFields: ['beforeField'],
      additionalRules: { positive: true },
      active: true,
      updatedAt: sameTimestamp,
    }
    ;(prisma.catalogValidationProfile.findMany as jest.Mock).mockResolvedValue([row])
    const preview = await previewCatalogValidationProfile(context, {
      idempotencyKey: 'profile-content-change',
      name: 'content hash',
      requiredFields: [],
    })
    const persisted = createdPreviewRecord()
    ;(prisma.catalogIdempotencyRecord.findFirst as jest.Mock).mockResolvedValue({
      id: 'profile-batch-content',
      organizationId: 'org-1',
      operation: 'VALIDATION_PROFILE_CHANGE',
      idempotencyKey: 'profile-content-change',
      state: 'PREVIEWED',
      targetHash: persisted.targetHash,
      previewTokenHash: persisted.previewTokenHash,
      previewExpiresAt: persisted.previewExpiresAt,
      dependencies: persisted.dependencies,
      actorType: 'HUMAN',
      staffId: 'staff-owner',
    })
    ;(prisma.catalogValidationProfile.findMany as jest.Mock).mockResolvedValue([{ ...row, requiredFields: ['afterField'] }])

    await expect(
      confirmCatalogValidationProfile(context, {
        profileBatchId: 'profile-batch-content',
        idempotencyKey: 'profile-content-change',
        previewToken: preview.previewToken,
        confirm: true,
      }),
    ).rejects.toMatchObject({ code: 'CATALOG_VALIDATION_PROFILE_STALE' })
  })

  it('keeps the idempotency row PREVIEWED when transactional audit fails', async () => {
    const preview = await previewCatalogValidationProfile(context, {
      idempotencyKey: 'profile-audit-rollback',
      name: 'audit rollback',
      requiredFields: ['supplierCode'],
    })
    const persisted = createdPreviewRecord()
    ;(prisma.catalogIdempotencyRecord.findFirst as jest.Mock).mockResolvedValue({
      id: 'profile-batch-audit',
      organizationId: 'org-1',
      operation: 'VALIDATION_PROFILE_CHANGE',
      idempotencyKey: 'profile-audit-rollback',
      state: 'PREVIEWED',
      targetHash: persisted.targetHash,
      previewTokenHash: persisted.previewTokenHash,
      previewExpiresAt: persisted.previewExpiresAt,
      dependencies: persisted.dependencies,
      actorType: 'HUMAN',
      staffId: 'staff-owner',
    })
    ;(writeCatalogAudit as jest.Mock).mockRejectedValueOnce(new Error('classified audit unavailable'))

    await expect(
      confirmCatalogValidationProfile(context, {
        profileBatchId: 'profile-batch-audit',
        idempotencyKey: 'profile-audit-rollback',
        previewToken: preview.previewToken,
        confirm: true,
      }),
    ).rejects.toThrow('classified audit unavailable')
    // WHY: The applied CAS is deliberately after audit; a thrown audit causes
    // the real transaction to roll back the new profile and scope deactivation.
    expect(prisma.catalogValidationProfile.create).toHaveBeenCalledTimes(1)
    expect(prisma.catalogIdempotencyRecord.updateMany).not.toHaveBeenCalled()
  })

  it('uses constant-time token verification and rejects stale dependency snapshots before writes', async () => {
    const preview = await previewCatalogValidationProfile(context, {
      idempotencyKey: 'profile-key-stale',
      name: 'PITS food STORE',
      requiredFields: ['supplierCode'],
    })
    const persisted = createdPreviewRecord()
    const record = {
      id: 'profile-batch-stale',
      organizationId: 'org-1',
      operation: 'VALIDATION_PROFILE_CHANGE',
      idempotencyKey: 'profile-key-stale',
      state: 'PREVIEWED',
      targetHash: persisted.targetHash,
      previewTokenHash: persisted.previewTokenHash,
      previewExpiresAt: persisted.previewExpiresAt,
      dependencies: persisted.dependencies,
      actorType: 'HUMAN',
      staffId: 'staff-owner',
    }
    ;(prisma.catalogIdempotencyRecord.findFirst as jest.Mock).mockResolvedValue(record)

    await expect(
      confirmCatalogValidationProfile(context, {
        profileBatchId: 'profile-batch-stale',
        idempotencyKey: 'profile-key-stale',
        previewToken: `${preview.previewToken}wrong`,
        confirm: true,
      }),
    ).rejects.toMatchObject({ statusCode: 409 })
    expect(prisma.catalogValidationProfile.create).not.toHaveBeenCalled()
    ;(prisma.catalogValidationProfile.findMany as jest.Mock).mockResolvedValue([
      {
        id: 'concurrent-profile',
        profileVersion: 1,
        rulesSchemaVersion: 1,
        businessType: null,
        operationalRole: null,
        requiredFields: ['concurrentField'],
        additionalRules: null,
        active: true,
        updatedAt: new Date('2026-08-08T12:01:00.000Z'),
      },
    ])
    await expect(
      confirmCatalogValidationProfile(context, {
        profileBatchId: 'profile-batch-stale',
        idempotencyKey: 'profile-key-stale',
        previewToken: preview.previewToken,
        confirm: true,
      }),
    ).rejects.toMatchObject({ statusCode: 409, code: 'CATALOG_VALIDATION_PROFILE_STALE' })
    expect(prisma.catalogValidationProfile.create).not.toHaveBeenCalled()
  })
})
